export const styles = {
  overlay: 'fixed inset-0 z-[100] flex items-end justify-center bg-foreground/45 p-0 backdrop-blur-[2px] md:items-center md:p-6',
  modal: 'flex max-h-[92dvh] w-full flex-col overflow-hidden rounded-t-3xl border border-border bg-card shadow-2xl md:max-h-[calc(100dvh-3rem)] md:max-w-3xl md:rounded-3xl',
  header: 'flex items-start justify-between gap-4 border-b border-border px-5 py-5 md:px-7 md:py-6',
  titleArea: 'min-w-0',
  title: 'text-2xl font-medium md:text-3xl',
  summary: 'mt-1.5 text-sm leading-6 text-muted-foreground md:text-base',
  effectiveDate: 'mt-2 text-xs font-medium text-primary',
  closeButton: 'flex h-10 w-10 shrink-0 cursor-pointer items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-secondary hover:text-primary',
  closeIcon: 'h-5 w-5',
  body: 'overflow-y-auto overscroll-contain px-5 py-1 md:px-7',
  section: 'border-b border-border py-5 last:border-b-0 md:py-6',
  sectionTitle: 'mb-3 text-base font-medium text-foreground md:text-lg',
  paragraphs: 'space-y-2.5',
  paragraph: 'whitespace-pre-line text-sm leading-7 text-muted-foreground md:text-[15px]',
  contactFormSection: 'border-b border-border py-5 last:border-b-0 md:py-6',
  contactForm: 'rounded-2xl border border-border bg-secondary/20 p-4 md:p-5',
  formGrid: 'grid gap-4 md:grid-cols-2',
  field: 'grid gap-2',
  messageField: 'mt-4 grid gap-2',
  label: 'text-sm font-medium text-foreground',
  input: 'min-h-11 rounded-xl border border-border bg-background px-3.5 text-sm text-foreground outline-none transition-colors placeholder:text-muted-foreground/70 focus:border-primary',
  select: 'min-h-11 cursor-pointer rounded-xl border border-border bg-background px-3.5 text-sm text-foreground outline-none transition-colors focus:border-primary',
  textarea: 'min-h-36 resize-y rounded-xl border border-border bg-background px-3.5 py-3 text-sm leading-6 text-foreground outline-none transition-colors placeholder:text-muted-foreground/70 focus:border-primary',
  checkboxField: 'mt-4 flex cursor-pointer items-start gap-2.5 text-sm leading-6 text-muted-foreground',
  checkbox: 'mt-1 h-4 w-4 shrink-0 cursor-pointer accent-primary',
  successMessage: 'mt-4 rounded-xl bg-primary/10 px-3.5 py-3 text-sm leading-6 text-primary',
  errorMessage: 'mt-4 rounded-xl bg-destructive/10 px-3.5 py-3 text-sm leading-6 text-destructive',
  formActions: 'mt-4 flex justify-end',
  submitButton: 'w-full cursor-pointer rounded-full bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 md:w-auto md:min-w-32',
  footer: 'border-t border-border bg-card px-5 py-4 md:px-7',
  confirmButton: 'w-full cursor-pointer rounded-full bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 md:ml-auto md:block md:w-auto md:min-w-28',
} as const;
