export const styles = {
  page: 'relative flex min-h-screen min-w-0 items-center bg-background px-8 py-6',
  shell: 'relative z-10 mx-auto w-full max-w-[1600px]',
  header: 'mb-8 flex items-center justify-between gap-6',
  title: 'text-[40px] font-medium leading-none tracking-tight text-foreground',
  live: (connected: boolean) => `flex items-center gap-2 rounded-full border px-4 py-2 text-xs font-medium [&>span]:h-2 [&>span]:w-2 [&>span]:rounded-full ${connected ? 'border-emerald-200 bg-emerald-50 text-emerald-700 [&>span]:bg-emerald-500 [&>span]:shadow-[0_0_0_4px_rgba(34,197,94,0.12)]' : 'border-border bg-secondary/60 text-muted-foreground [&>span]:bg-muted-foreground/50'}`,
  tabBar: 'mb-5 grid grid-flow-col auto-cols-[minmax(110px,1fr)] items-center gap-1 overflow-x-auto rounded-[24px] border border-primary/15 bg-card/90 p-1.5 shadow-sm shadow-primary/5',
  tab: (active: boolean) => `flex h-10 min-w-0 items-center justify-center gap-2 rounded-full px-3 text-xs font-medium transition-all [&>svg]:h-4 [&>svg]:w-4 [&>svg]:shrink-0 [&>span]:truncate ${active ? 'bg-primary text-primary-foreground shadow-md shadow-primary/20' : 'text-muted-foreground hover:bg-primary/[0.06] hover:text-primary'}`,
  contentArea: 'min-w-0 space-y-5',
  hero: 'relative flex min-h-[150px] items-center overflow-hidden rounded-[28px] border border-primary/15 bg-gradient-to-br from-primary/[0.10] via-card to-card px-8 py-7 shadow-sm shadow-primary/5 before:absolute before:-right-16 before:-top-20 before:h-60 before:w-60 before:rounded-full before:bg-primary/[0.08] [&>div:first-child]:relative [&>div:first-child>span]:text-xs [&>div:first-child>span]:font-semibold [&>div:first-child>span]:text-primary [&_h2]:mt-2 [&_h2]:text-2xl [&_h2]:font-medium [&_p]:mt-2 [&_p]:text-sm [&_p]:text-muted-foreground',
  stats: 'grid grid-cols-2 gap-3 lg:grid-cols-4',
  stat: 'group relative overflow-hidden rounded-[22px] border border-border/80 bg-card px-5 py-5 shadow-sm shadow-black/[0.025] transition-all hover:-translate-y-0.5 hover:border-primary/30 hover:bg-primary/[0.025] hover:shadow-md hover:shadow-primary/10 [&>span]:block [&>span]:text-xs [&>span]:text-muted-foreground [&>strong]:mt-2 [&>strong]:block [&>strong]:text-2xl [&>strong]:font-medium [&>small]:mt-4 [&>small]:flex [&>small]:items-center [&>small]:gap-1 [&>small]:text-[11px] [&>small]:font-medium [&>small]:text-primary [&>small>svg]:h-3 [&>small>svg]:w-3 [&>small>svg]:transition-transform group-hover:[&>small>svg]:translate-x-0.5',
  infoStat: 'rounded-2xl border border-primary/10 bg-card p-5 shadow-sm [&>span]:block [&>span]:text-xs [&>span]:text-muted-foreground [&>strong]:mt-2 [&>strong]:block [&>strong]:truncate [&>strong]:text-xl [&>strong]:font-medium',
  panel: 'overflow-hidden rounded-[28px] border border-primary/15 bg-card/95 shadow-sm shadow-primary/5',
  toolbar: 'flex items-center justify-between gap-4 border-b border-primary/10 bg-primary/[0.018] p-5',
  toolbarActions: 'flex shrink-0 items-center gap-2 [&>button]:h-9 [&>button]:rounded-full [&>button]:px-4 [&>button]:text-xs',
  filterSelect: 'h-9 w-36 rounded-xl border-border bg-card px-3 text-xs text-foreground shadow-sm hover:bg-secondary/40 focus:border-border focus:ring-0 data-[state=open]:bg-secondary/40 data-[state=open]:ring-0',
  filterContent: 'rounded-xl border-border bg-card p-1 shadow-lg',
  filterItem: 'cursor-pointer rounded-lg text-xs focus:bg-secondary focus:text-foreground data-[highlighted]:bg-secondary data-[highlighted]:text-foreground data-[state=checked]:font-medium',
  secondaryButton: 'rounded-full border-border text-foreground hover:border-border hover:bg-secondary hover:text-foreground',
  search: 'relative max-w-md flex-1 [&_svg]:absolute [&_svg]:left-4 [&_svg]:top-1/2 [&_svg]:h-4 [&_svg]:w-4 [&_svg]:-translate-y-1/2 [&_svg]:text-muted-foreground',
  input: 'h-10 rounded-full border-primary/10 bg-card pl-11',
  count: 'rounded-full bg-primary/10 px-3 py-1.5 text-xs font-medium text-primary',
  tableWrap: 'min-h-[560px] overflow-auto',
  table: 'w-full min-w-[900px] border-collapse text-left',
  th: 'whitespace-nowrap border-b border-primary/10 bg-primary/[0.035] px-5 py-4 text-xs font-medium text-muted-foreground',
  tableRow: (interactive: boolean) => `transition-colors hover:bg-primary/[0.025] ${interactive ? 'cursor-pointer focus:bg-primary/[0.04] focus:outline-none' : ''}`,
  td: 'max-w-[280px] truncate whitespace-nowrap border-b border-primary/10 px-5 py-4 text-sm',
  empty: 'flex min-h-[540px] flex-col items-center justify-center px-6 text-center [&>svg]:mb-4 [&>svg]:h-10 [&>svg]:w-10 [&>svg]:text-primary/35 [&>strong]:text-sm [&>span]:mt-1.5 [&>span]:text-xs [&>span]:text-muted-foreground',
  pagination: 'flex min-h-16 items-center justify-center gap-1 border-t border-primary/10',
  paginationOutside: 'mt-5 flex min-h-10 items-center justify-center gap-1',
  pageButton: (active = false) => `flex h-9 min-w-9 items-center justify-center rounded-full px-3 text-xs font-medium ${active ? 'bg-primary text-primary-foreground shadow-sm shadow-primary/20' : 'text-muted-foreground hover:bg-primary/10 hover:text-primary'} disabled:pointer-events-none disabled:opacity-30`,
  homeGrid: 'grid grid-cols-2 gap-5',
  miniPanel: 'overflow-hidden rounded-[26px] border border-primary/10 bg-card p-5 shadow-sm [&>header]:mb-2 [&>header]:flex [&>header]:items-center [&>header]:justify-between [&_h2]:text-base [&_h2]:font-medium [&>header>a]:flex [&>header>a]:items-center [&>header>a]:gap-1 [&>header>a]:text-xs [&>header>a]:font-medium [&>header>a]:text-primary [&>header>a>svg]:h-3.5 [&>header>a>svg]:w-3.5',
  miniRow: 'flex items-center justify-between gap-3 border-b border-primary/10 py-3.5 text-sm transition-colors last:border-0 hover:text-primary [&>span]:min-w-0 [&_strong]:block [&_strong]:truncate [&_small]:mt-1 [&_small]:block [&_small]:truncate [&_small]:text-xs [&_small]:font-normal [&_small]:text-muted-foreground [&>svg]:h-4 [&>svg]:w-4 [&>svg]:shrink-0 [&>svg]:text-muted-foreground/50',
  miniEmpty: 'py-10 text-center text-xs text-muted-foreground',
  overlay: 'fixed inset-0 z-[70] flex items-center justify-center bg-foreground/20 p-6 backdrop-blur-sm',
  userModal: 'max-h-[92vh] w-full max-w-[760px] overflow-hidden rounded-[28px] border border-primary/15 bg-card shadow-2xl shadow-primary/15',
  modalHeader: 'flex items-center justify-between border-b border-primary/10 px-6 py-5 [&>div:first-child]:flex [&>div:first-child]:items-center [&>div:first-child]:gap-4 [&_h2]:text-xl [&_h2]:font-medium [&_p]:mt-1 [&_p]:text-sm [&_p]:text-muted-foreground [&>button]:rounded-full [&>button:hover]:bg-secondary [&>button:hover]:text-foreground',
  userAvatar: 'flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-primary/10 text-lg font-medium text-primary [&_img]:h-full [&_img]:w-full [&_img]:object-cover [&_svg]:h-5 [&_svg]:w-5',
  modalBody: 'max-h-[calc(92vh-96px)] space-y-5 overflow-y-auto p-6',
  detailGrid: 'grid grid-cols-3 gap-3 [&>span]:rounded-2xl [&>span]:border [&>span]:border-primary/10 [&>span]:bg-primary/[0.02] [&>span]:p-4 [&_small]:block [&_small]:text-xs [&_small]:text-muted-foreground [&_strong]:mt-2 [&_strong]:block [&_strong]:truncate [&_strong]:text-sm [&_strong]:font-medium',
  manageSection: 'rounded-2xl border border-primary/10 p-5',
  manageHeading: 'flex items-center gap-3 [&>svg]:h-5 [&>svg]:w-5 [&>svg]:shrink-0 [&>svg]:text-primary [&>div]:min-w-0 [&_strong]:block [&_strong]:text-sm [&_span]:mt-1 [&_span]:block [&_span]:text-xs [&_span]:text-muted-foreground [&>em]:ml-auto',
  optionRow: 'mt-4 grid grid-cols-2 gap-3',
  option: (active: boolean) => `flex h-11 items-center justify-center gap-2 rounded-xl border text-sm font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-45 [&>svg]:h-4 [&>svg]:w-4 ${active ? 'border-primary/30 bg-primary/10 text-primary' : 'border-border text-muted-foreground hover:bg-secondary hover:text-foreground'}`,
  dangerOption: (active: boolean) => `flex h-11 items-center justify-center gap-2 rounded-xl border text-sm font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-45 [&>svg]:h-4 [&>svg]:w-4 ${active ? 'border-destructive bg-destructive text-white' : 'border-destructive/25 text-destructive hover:bg-destructive/10'}`,
  statusBadge: (status: string) => `rounded-full px-3 py-1.5 text-[11px] font-medium not-italic ${status === 'ACTIVE' ? 'bg-emerald-100 text-emerald-700' : status === 'INACTIVE' ? 'bg-amber-100 text-amber-700' : 'bg-secondary text-muted-foreground'}`,
  dangerZone: 'flex items-center justify-between gap-5 rounded-2xl border border-destructive/15 bg-destructive/[0.025] p-5 [&>div]:flex [&>div]:items-center [&>div]:gap-3 [&>div>svg]:h-5 [&>div>svg]:w-5 [&>div>svg]:shrink-0 [&>div>svg]:text-destructive [&_strong]:block [&_strong]:text-sm [&_small]:mt-1 [&_small]:block [&_small]:text-xs [&_small]:text-muted-foreground [&>button]:shrink-0 [&>button]:rounded-full',
  itemDetailGrid: 'grid grid-cols-3 gap-3 [&>span]:min-w-0 [&>span]:rounded-2xl [&>span]:border [&>span]:border-primary/10 [&>span]:bg-primary/[0.02] [&>span]:p-4 [&_small]:block [&_small]:text-xs [&_small]:text-muted-foreground [&_strong]:mt-2 [&_strong]:block [&_strong]:truncate [&_strong]:text-sm [&_strong]:font-medium',
  memoField: 'block [&>span]:mb-2 [&>span]:block [&>span]:text-sm [&>span]:font-medium [&>textarea]:min-h-28 [&>textarea]:w-full [&>textarea]:resize-none [&>textarea]:rounded-2xl [&>textarea]:border [&>textarea]:border-primary/15 [&>textarea]:bg-input-background [&>textarea]:p-4 [&>textarea]:text-sm [&>textarea]:outline-none focus:[&>textarea]:border-primary',
  itemActions: 'flex flex-wrap justify-end gap-2 border-t border-primary/10 pt-5 [&>button]:rounded-full [&>button]:px-5 [&>button]:shadow-none',
  systemGuide: 'flex items-start gap-4 rounded-[24px] border border-border bg-card p-6 shadow-sm [&>svg]:h-6 [&>svg]:w-6 [&>svg]:shrink-0 [&>svg]:text-primary [&_strong]:text-sm [&_p]:mt-1.5 [&_p]:max-w-3xl [&_p]:text-xs [&_p]:leading-5 [&_p]:text-muted-foreground',
} as const;
