export const styles = {
  page: 'min-h-screen bg-background',
  header: 'border-b border-border bg-card px-4 py-4',
  logoWrapper: 'justify-center',
  content: 'max-w-2xl mx-auto px-4 py-12 space-y-8',
  stack: 'text-center space-y-4',
  row: 'w-24 h-24 rounded-full bg-gradient-to-br from-primary/20 to-primary/5 mx-auto flex items-center justify-center mb-4',
  checkIcon: 'w-12 h-12 text-primary',
  pageTitle: 'text-4xl font-medium mb-3',
  descriptionText: 'text-lg text-muted-foreground',
  header2: 'bg-card border-2 border-border rounded-3xl p-8 md:p-10 shadow-sm',
  sectionHeader: 'mb-8 pb-8 border-b border-border',
  mediaRow: 'flex items-start gap-4 mb-6',
  row2: 'w-14 h-14 rounded-2xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center flex-shrink-0',
  usersIcon: 'w-7 h-7 text-primary',
  row3: 'flex-1',
  sectionTitle: 'text-2xl font-medium mb-2',
  statsGrid: 'grid md:grid-cols-3 gap-4',
  row4: 'flex items-center gap-3 p-4 bg-secondary/30 rounded-xl',
  calendarIcon: 'w-5 h-5 text-primary flex-shrink-0',
  textContent: 'min-w-0',
  descriptionText2: 'text-xs text-muted-foreground',
  summaryText: 'font-medium truncate',
  stack2: 'space-y-4',
  fullWidthButton: 'w-full rounded-2xl h-auto p-7 shadow-lg shadow-primary/20',
  row5: 'flex items-center gap-4 w-full',
  row6: 'w-16 h-16 rounded-xl bg-primary-foreground/20 flex items-center justify-center',
  checkIcon2: 'w-8 h-8 text-primary-foreground',
  row7: 'flex-1 text-left',
  summaryText2: 'text-2xl font-medium',
  paragraphText: 'text-sm opacity-90',
  cardLink: 'block',
  fullWidthButton2: 'w-full rounded-2xl h-auto p-6 border-2',
  row8: 'w-12 h-12 rounded-xl bg-secondary flex items-center justify-center',
  clockIcon: 'w-6 h-6 text-primary',
  summaryText3: 'text-lg font-medium',
  descriptionText3: 'text-sm text-muted-foreground',
  fullWidthButton3: 'w-full rounded-2xl h-auto p-6 border-2 border-destructive/30 hover:bg-destructive/5',
  row9: 'w-12 h-12 rounded-xl bg-destructive/10 flex items-center justify-center',
  xIcon: 'w-6 h-6 text-destructive',
  summaryText4: 'text-lg font-medium text-destructive',
  contentBox: 'bg-gradient-to-br from-accent/20 to-accent/5 rounded-2xl p-6 border-2 border-accent/40',
  mediaRow2: 'flex items-start gap-3',
  row10: 'w-8 h-8 rounded-full bg-accent/30 flex items-center justify-center flex-shrink-0',
  labelText: 'text-sm font-medium text-accent-foreground',
  stack3: 'space-y-1',
  summaryText5: 'font-medium text-accent-foreground',
  paragraphText2: 'text-sm text-accent-foreground/80',
  header3: 'fixed left-4 right-4 bottom-4 bg-card border border-border rounded-2xl p-4 shadow-xl text-center text-sm font-medium',
} as const;
