export const styles = {
  page: 'min-h-screen bg-background',
  header: 'border-b border-border bg-card',
  headerInner: 'max-w-7xl mx-auto px-6 py-4 flex items-center justify-between',
  row: 'flex items-center gap-6',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  content: 'max-w-7xl mx-auto px-6 py-8',
  sectionHeader: 'mb-8',
  pageTitle: 'text-4xl font-medium mb-2',
  descriptionText: 'text-muted-foreground',
  cardGrid: 'grid grid-cols-2 gap-6',
  header2: 'bg-card border border-border rounded-2xl p-6',
  betweenRow: 'flex items-center justify-between mb-6',
  row2: 'flex items-center gap-3',
  badge: 'bg-primary text-primary-foreground text-lg px-4 py-2',
  mutedText: 'text-sm text-muted-foreground',
  roundButton: 'rounded-full gap-2',
  stack: 'space-y-4',
  summaryBox: 'bg-secondary rounded-xl p-4',
  descriptionText2: 'text-xs text-muted-foreground mb-3',
  stack2: 'space-y-2',
  row3: 'w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center',
  labelText: 'text-sm font-medium text-primary',
  summaryText: 'font-medium',
  descriptionText3: 'text-xs text-muted-foreground',
  centeredBlock: 'text-center py-2',
  mutedText2: 'text-xl font-medium text-muted-foreground',
  row4: 'mt-4 flex gap-3',
  roundButton2: 'flex-1 rounded-full',
  floatingNotice: 'fixed bottom-6 left-1/2 -translate-x-1/2 bg-card border border-border rounded-full px-5 py-3 shadow-xl text-sm font-medium',
} as const;
