export const styles = {
  page: 'min-h-screen bg-gradient-to-br from-background via-secondary/10 to-primary/5 p-8',
  content: 'max-w-[1920px] mx-auto space-y-8',
  betweenRow: 'flex items-center justify-between',
  row: 'flex items-center gap-6',
  pageTitle: 'text-3xl mb-1',
  descriptionText: 'text-xl text-muted-foreground',
  rightAlignedBlock: 'text-right',
  summaryText: 'text-5xl font-medium text-primary',
  descriptionText2: 'text-lg text-muted-foreground',
  row2: 'flex items-center gap-3 mb-6',
  sectionTitle: 'text-4xl',
  badge: 'bg-primary text-primary-foreground text-lg px-4 py-2',
  cardGrid: 'grid grid-cols-2 gap-6',
  header: 'bg-card border-2 border-border rounded-3xl p-8 shadow-lg',
  row3: 'flex items-center gap-4 mb-8',
  row4: 'w-20 h-20 rounded-2xl bg-primary flex items-center justify-center',
  labelText: 'text-4xl font-medium text-primary-foreground',
  summaryText2: 'text-3xl font-medium',
  stack: 'space-y-6',
  summaryBox: 'bg-secondary rounded-2xl p-6',
  descriptionText3: 'text-lg text-muted-foreground mb-4',
  stack2: 'space-y-3',
  centeredBlock: 'text-center py-2',
  mutedText: 'text-4xl font-medium text-muted-foreground',
  sectionTitle2: 'text-4xl mb-6',
  header2: 'bg-card/50 border border-border rounded-3xl p-8',
  statsGrid: 'grid grid-cols-3 gap-4 items-center',
  summaryBox2: 'bg-secondary/50 rounded-xl p-4',
  stack3: 'space-y-2',
  summaryText3: 'text-xl font-medium',
  centeredBlock2: 'text-center',
  mutedText2: 'text-3xl font-medium text-muted-foreground',
  contentBox: 'bg-accent/20 border-2 border-accent rounded-3xl p-8',
  qrCodeIcon: 'w-16 h-16 text-accent-foreground',
  cardTitle: 'text-3xl font-medium text-accent-foreground mb-2',
  paragraphText: 'text-xl text-accent-foreground/80',
  row5: 'w-32 h-32 bg-card rounded-2xl flex items-center justify-center',
  qrCodeIcon2: 'w-20 h-20 text-muted-foreground',
} as const;
