export const styles = {
  page: 'min-h-screen bg-gradient-to-b from-background to-secondary/20',
  header: 'border-b border-border bg-card',
  content: 'max-w-7xl mx-auto px-6 py-6',
  logoWrapper: 'justify-center',
  content2: 'max-w-7xl mx-auto px-6 py-12',
  sectionHeader: 'text-center mb-12',
  pageTitle: 'text-4xl font-medium mb-4',
  descriptionText: 'text-xl text-muted-foreground',
  stack: 'space-y-12',
  row: 'flex items-center gap-4 mb-8',
  row2: 'w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center',
  monitorIcon: 'w-6 h-6 text-primary',
  sectionTitle: 'text-3xl font-medium',
  descriptionText2: 'text-muted-foreground',
  badge: 'ml-auto bg-primary text-primary-foreground',
  statsGrid: 'grid md:grid-cols-2 lg:grid-cols-3 gap-6',
  header2: 'bg-card border-2 border-border rounded-2xl p-6 hover:border-primary transition-all hover:shadow-xl group',
  betweenRow: 'flex items-start justify-between mb-4',
  row3: 'flex-1',
  cardTitle: 'text-xl font-medium mb-2 group-hover:text-primary transition-colors',
  descriptionText3: 'text-sm text-muted-foreground line-clamp-2',
  chevronRightIcon: 'w-5 h-5 text-muted-foreground group-hover:text-primary transition-colors ml-2 flex-shrink-0',
  footerActions: 'pt-4 border-t border-border',
  fullWidthButton: 'w-full rounded-full',
  contentBox: 'mt-12 bg-gradient-to-br from-secondary/50 to-transparent rounded-3xl p-8 border border-border text-center',
  cardTitle2: 'text-xl font-medium mb-3',
  descriptionText4: 'text-muted-foreground mb-6',
  roundButton: 'rounded-full',
} as const;
