export const styles = {
  page: 'relative flex min-h-screen min-w-0 items-center bg-background px-8 py-6',
  content2: 'relative z-10 mx-auto w-full max-w-[1600px]',
  sectionHeader: 'mb-8',
  pageTitle: 'text-[40px] font-medium leading-none tracking-tight text-foreground',
  stack: 'space-y-12',
  row: 'flex items-center gap-4 mb-8',
  row2: 'w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center',
  monitorIcon: 'w-6 h-6 text-primary',
  sectionTitle: 'text-xl font-medium',
  descriptionText2: 'mt-1 text-sm text-muted-foreground',
  badge: 'ml-auto bg-primary text-primary-foreground',
  statsGrid: 'grid gap-4 md:grid-cols-2 lg:grid-cols-3',
  header2: 'group rounded-[24px] border border-primary/15 bg-card/90 p-5 shadow-sm shadow-primary/5 transition-all hover:-translate-y-0.5 hover:border-primary/30 hover:bg-primary/[0.025] hover:shadow-md hover:shadow-primary/10',
  betweenRow: 'flex items-start justify-between mb-4',
  row3: 'flex-1',
  cardTitle: 'text-xl font-medium mb-2 group-hover:text-primary transition-colors',
  descriptionText3: 'text-sm text-muted-foreground line-clamp-2',
  chevronRightIcon: 'w-5 h-5 text-muted-foreground group-hover:text-primary transition-colors ml-2 flex-shrink-0',
  footerActions: 'pt-4 border-t border-border',
  fullWidthButton: 'w-full rounded-full',
  contentBox: 'mt-12 bg-gradient-to-br from-secondary/50 to-transparent rounded-3xl p-8 border border-border text-center',
  cardTitle2: 'text-xl font-medium mb-3',
  descriptionText4: 'text-muted-foreground mb-6',
  roundButton: 'rounded-full',
} as const;
