export const styles = {
  contentBox: 'p-8',
  sectionHeader: 'mb-8',
  betweenRow: 'flex items-center justify-between mb-4',
  pageTitle: 'text-3xl mb-2',
  descriptionText: 'text-muted-foreground text-lg',
  roundButton: 'rounded-full gap-2 h-12 px-6 shadow-lg shadow-primary/20',
  plusCircleIcon: 'w-5 h-5',
  statsGrid: 'grid grid-cols-3 gap-6 mb-8',
  contentBox2: 'bg-gradient-to-br from-card to-card/50 border-2 border-primary/20 rounded-2xl p-6',
  betweenRow2: 'flex items-start justify-between mb-4',
  row: 'w-14 h-14 rounded-2xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center',
  usersIcon: 'w-7 h-7 text-primary',
  trendingUpIcon: 'w-5 h-5 text-primary',
  descriptionText2: 'text-sm text-muted-foreground mb-1',
  summaryText: 'text-4xl font-medium',
  header: 'bg-card border border-border rounded-2xl p-6',
  row2: 'w-14 h-14 rounded-2xl bg-secondary flex items-center justify-center',
  cardGrid: 'grid grid-cols-2 gap-6',
  cardLink: 'block group',
  header2: 'bg-card border border-border rounded-3xl overflow-hidden hover:border-primary transition-all hover:shadow-xl',
  contentBox3: 'bg-gradient-to-r from-secondary/50 to-transparent p-6 border-b border-border',
  row3: 'flex-1',
  cardTitle: 'text-xl font-medium mb-2 group-hover:text-primary transition-colors',
  row4: 'flex items-center gap-4 text-sm text-muted-foreground',
  row5: 'flex items-center gap-1.5',
  mapPinIcon: 'w-4 h-4',
  row6: 'w-14 h-14 rounded-2xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center group-hover:scale-110 transition-transform',
  contentBox4: 'p-6',
  statsGrid2: 'grid grid-cols-3 gap-4 mb-6',
  centeredBlock: 'text-center',
  summaryText2: 'text-2xl font-medium text-primary',
  descriptionText3: 'text-xs text-muted-foreground mt-1',
  centeredBlock2: 'text-center border-x border-border',
  betweenRow3: 'flex items-center justify-between mb-4 pb-4 border-b border-border',
  row7: 'flex items-center gap-2 text-sm',
  calendarIcon: 'w-4 h-4 text-muted-foreground',
  mutedText: 'text-muted-foreground',
  cardGrid2: 'grid grid-cols-2 gap-3',
  roundButton2: 'rounded-full',
  cardLink2: 'block',
  stack: 'bg-gradient-to-br from-secondary/50 to-secondary/20 border-2 border-dashed border-border rounded-3xl p-8 flex flex-col items-center justify-center text-center space-y-6 hover:border-primary transition-colors cursor-pointer',
  row8: 'w-20 h-20 rounded-full bg-card flex items-center justify-center',
  plusCircleIcon2: 'w-10 h-10 text-primary',
  cardTitle2: 'text-xl font-medium mb-2',
  roundButton3: 'rounded-full gap-2',
} as const;
