export const styles = {
  page: 'min-h-screen bg-background',
  header: 'border-b border-border bg-card',
  content: 'max-w-4xl mx-auto px-4 md:px-8 py-4',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  content2: 'max-w-4xl mx-auto px-4 md:px-8 py-12',
  sectionHeader: 'text-center mb-12',
  row: 'w-20 h-20 rounded-full bg-gradient-to-br from-primary/20 to-primary/5 mx-auto flex items-center justify-center mb-6',
  usersIcon: 'w-10 h-10 text-primary',
  pageTitle: 'text-4xl font-medium mb-3',
  descriptionText: 'text-lg text-muted-foreground',
  header2: 'bg-card border border-border rounded-3xl p-8 md:p-10 shadow-sm',
  form: 'space-y-8',
  sectionTitle: 'text-xl font-medium mb-6 flex items-center gap-3',
  row2: 'w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center',
  usersIcon2: 'w-4 h-4 text-primary',
  stack: 'space-y-6',
  stack2: 'space-y-2',
  input: 'rounded-xl h-12',
  descriptionText2: 'text-sm text-muted-foreground',
  inputWrapper: 'relative',
  mapPinIcon: 'absolute left-4 top-1/2 transform -translate-y-1/2 w-4 h-4 text-muted-foreground',
  input2: 'rounded-xl h-12 pl-11',
  textareaIcon: 'rounded-xl resize-none',
  footerActions: 'border-t border-border pt-8',
  summaryBox: 'bg-secondary/30 rounded-2xl p-6',
  cardTitle: 'font-medium mb-3',
  list: 'space-y-2 text-sm text-muted-foreground',
  listItem: 'flex items-start gap-2',
  row3: 'w-1.5 h-1.5 rounded-full bg-primary mt-1.5 flex-shrink-0',
  footerActions2: 'border-t border-border pt-8 flex gap-4',
  link: 'flex-1',
  fullWidthButton: 'w-full rounded-full h-12',
  submitButton: 'flex-1 rounded-full h-12 shadow-lg shadow-primary/20',
  usersIcon3: 'w-5 h-5 mr-2',
  centeredBlock: 'mt-8 text-center',
} as const;
