export const styles = {
  page: 'min-h-screen bg-background',
  header: 'border-b border-border bg-card',
  headerInner: 'max-w-7xl mx-auto px-6 py-4 flex items-center justify-between',
  row: 'flex items-center gap-6',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  content: 'max-w-7xl mx-auto px-6 py-8',
  sectionHeader: 'mb-6',
  pageTitle: 'text-4xl font-medium mb-2',
  descriptionText: 'text-muted-foreground',
  grid: 'grid grid-cols-4 gap-4 mb-6',
  card: 'bg-card border-2 border-primary/30 rounded-xl p-5 text-center',
  summaryText: 'text-3xl font-medium text-primary mb-1',
  descriptionText2: 'text-sm text-muted-foreground',
  header2: 'bg-card border border-border rounded-xl p-5 text-center',
  summaryText2: 'text-3xl font-medium mb-1',
  header3: 'bg-card border border-border rounded-2xl p-6 mb-6',
  row2: 'flex gap-4',
  row3: 'flex-1 relative',
  searchIcon: 'absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-muted-foreground',
  input: 'pl-10 rounded-full',
  selectTrigger: 'w-40 rounded-full',
  filterIcon: 'w-4 h-4 mr-2',
  statsGrid: 'grid md:grid-cols-2 lg:grid-cols-3 gap-4',
  header4: 'bg-card border border-border rounded-2xl p-6 hover:border-primary transition-all',
  mediaRow: 'flex items-start gap-4 mb-4',
  row4: 'w-16 h-16 rounded-full bg-primary/20 flex items-center justify-center flex-shrink-0',
  labelText: 'text-2xl font-medium text-primary',
  row5: 'flex-1 min-w-0',
  cardTitle: 'text-xl font-medium mb-1',
  wrapRow: 'flex items-center gap-2 flex-wrap',
  badge: 'bg-primary text-primary-foreground',
  footerActions: 'grid grid-cols-2 gap-3 pt-4 border-t border-border',
  summaryBox: 'bg-secondary rounded-xl p-3 text-center',
  row6: 'flex items-center justify-center gap-1 mb-1',
  calendarIcon: 'w-4 h-4 text-muted-foreground',
  summaryText3: 'text-xl font-medium text-primary',
  descriptionText3: 'text-xs text-muted-foreground',
  mutedText: 'pt-3 text-center text-sm text-muted-foreground',
  contentBox: 'mt-8 bg-gradient-to-br from-accent/20 to-accent/5 border-2 border-accent/40 rounded-3xl p-8',
  row7: 'w-16 h-16 rounded-2xl bg-accent/30 flex items-center justify-center flex-shrink-0',
  usersIcon: 'w-8 h-8 text-accent-foreground',
  row8: 'flex-1',
  cardTitle2: 'text-xl font-medium mb-2',
  descriptionText4: 'text-muted-foreground mb-4',
  roundButton: 'rounded-full',
  floatingNotice: 'fixed bottom-6 left-1/2 -translate-x-1/2 bg-card border border-border rounded-full px-5 py-3 shadow-xl text-sm font-medium',
} as const;
