export const styles = {
  page: 'min-h-screen bg-background',
  content: 'max-w-5xl mx-auto px-4 md:px-8 py-8 space-y-8',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  contentBox: 'bg-gradient-to-br from-card to-secondary/10 border-2 border-border rounded-3xl p-8 md:p-10 shadow-sm',
  betweenRow: 'flex items-start justify-between mb-8',
  mediaRow: 'flex items-start gap-6',
  row: 'w-20 h-20 rounded-2xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center flex-shrink-0',
  usersIcon: 'w-10 h-10 text-primary',
  stack: 'space-y-4',
  pageTitle: 'text-4xl mb-3',
  stack2: 'space-y-2 text-muted-foreground',
  row2: 'flex items-center gap-2',
  roundButton: 'rounded-full flex-shrink-0',
  cardGrid: 'grid md:grid-cols-2 gap-4',
  cardLink: 'block',
  fullWidthButton: 'w-full rounded-full h-12 shadow-lg shadow-primary/20',
  calendarIcon: 'w-5 h-5 mr-2',
  roundButton2: 'rounded-full h-12 gap-2',
  share2Icon: 'w-5 h-5',
  header: 'bg-card border border-border rounded-3xl p-8 space-y-6',
  betweenRow2: 'flex items-center justify-between',
  sectionTitle: 'text-2xl font-medium',
  actionButton: 'text-primary',
  grid: 'grid gap-3',
  contentBox2: 'bg-gradient-to-r from-secondary/50 to-transparent rounded-2xl p-5 border border-border hover:border-primary transition-all group cursor-pointer',
  row3: 'flex items-center gap-4',
  row4: 'w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center',
  calendarIcon2: 'w-6 h-6 text-primary',
  summaryText: 'font-medium text-lg mb-1',
  descriptionText: 'text-sm text-muted-foreground',
  row5: 'flex items-center gap-3',
  rightAlignedBlock: 'text-right',
  summaryText2: 'text-lg font-medium text-primary',
  cardGrid2: 'grid md:grid-cols-2 gap-3',
  contentBox3: 'bg-gradient-to-r from-secondary/50 to-transparent rounded-2xl p-5 border border-border hover:border-primary transition-all',
  row6: 'w-12 h-12 rounded-full bg-primary/20 flex items-center justify-center',
  row7: 'flex-1',
  summaryText3: 'font-medium text-lg',
  summaryText4: 'font-medium text-primary',
  contentBox4: 'bg-gradient-to-br from-accent/20 to-accent/5 border-2 border-accent/40 rounded-3xl p-8',
  row8: 'w-16 h-16 rounded-2xl bg-accent/30 flex items-center justify-center flex-shrink-0',
  qrCodeIcon: 'w-8 h-8 text-accent-foreground',
  cardTitle: 'text-xl font-medium mb-2',
  descriptionText2: 'text-muted-foreground mb-6',
  row9: 'flex gap-3',
  roundButton3: 'rounded-full gap-2',
  floatingNotice: 'fixed bottom-6 left-1/2 -translate-x-1/2 bg-card border border-border rounded-full px-5 py-3 shadow-xl text-sm font-medium',
} as const;
