const basePanel = 'rounded-[26px] border border-primary/15 bg-card/95 shadow-sm shadow-primary/5';

export const styles = {
  page: 'relative h-dvh min-w-0 flex-1 overflow-x-hidden overflow-y-auto bg-background px-8 pb-4 pt-2 [scrollbar-gutter:stable]',
  backgroundGlowTop: 'pointer-events-none fixed right-12 top-16 h-72 w-72 rounded-full bg-primary/5 blur-3xl',
  backgroundGlowBottom: 'pointer-events-none fixed bottom-10 left-72 h-64 w-64 rounded-full bg-primary/5 blur-3xl',
  pageShell: 'relative z-10 mx-auto w-full max-w-[1600px] pt-5',
  backLink: 'fixed left-[calc(16rem+2rem)] top-8 z-20 inline-flex items-center gap-2 text-sm text-muted-foreground transition-colors hover:text-primary',
  smallIcon: 'h-4 w-4',
  groupHeader: `${basePanel} flex min-w-0 items-start justify-between gap-8 p-7`,
  groupIdentity: 'flex min-w-0 items-center gap-6',
  groupImage: 'h-[104px] w-[104px] shrink-0 rounded-[28px] object-cover shadow-md shadow-primary/10',
  groupHeaderText: 'min-w-0',
  titleRow: 'flex min-w-0 items-center gap-3',
  title: 'truncate text-[32px] font-medium tracking-tight text-foreground',
  ownerBadge: 'h-7 rounded-full bg-primary/10 px-3 text-primary',
  groupDescription: 'mt-2 max-w-3xl text-sm leading-6 text-muted-foreground',
  groupMeta: 'mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-muted-foreground [&_span]:flex [&_span]:items-center [&_span]:gap-1.5 [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:text-primary/70',
  headerActions: 'flex shrink-0 flex-wrap justify-end gap-2',
  roundButton: 'h-10 rounded-full border-primary/15 px-4 hover:border-primary/30 hover:bg-primary/10 hover:text-primary',
  smallRoundButton: 'h-9 rounded-full border-primary/15 px-4 hover:border-primary/30 hover:bg-primary/10 hover:text-primary',
  destructiveButton: 'hover:border-destructive/40 hover:bg-destructive/90 hover:text-white',
  leaveButton: 'h-10 rounded-full px-3 text-muted-foreground hover:bg-destructive/5 hover:text-destructive',
  tabBar: `${basePanel} mt-4 grid grid-cols-7 items-center gap-1 p-1.5`,
  tabButton: (active: boolean) => `relative inline-flex h-10 min-w-0 items-center justify-center rounded-full px-3 text-center text-sm font-medium transition-all ${active ? 'bg-primary text-primary-foreground shadow-md shadow-primary/20' : 'text-muted-foreground hover:bg-primary/[0.06] hover:text-primary'} [&_span]:ml-2 [&_span]:rounded-full [&_span]:bg-white/20 [&_span]:px-1.5 [&_span]:py-0.5 [&_span]:text-[10px]`,
  tabContent: 'mt-5 min-w-0',
  paginatedTab: 'flex h-[calc(100dvh-19.5rem)] min-h-0 flex-col overflow-hidden',
  listTabPanel: 'flex min-h-0 flex-1 flex-col',
  listTabBody: 'flex min-h-0 flex-1 flex-col pb-0',
  homeGrid: 'min-w-0 space-y-5',
  homeTopGrid: 'grid min-w-0 grid-cols-[minmax(0,1.45fr)_minmax(360px,0.75fr)] items-stretch gap-5',
  mainColumn: 'min-w-0 space-y-5',
  sideColumn: 'min-w-0 [&>section]:h-full',
  panel: `${basePanel} min-w-0 overflow-hidden`,
  panelHeader: 'flex min-h-[82px] items-center justify-between gap-5 border-b border-primary/10 bg-gradient-to-r from-primary/[0.035] via-card to-card px-6 py-4',
  panelTitleBox: 'flex min-w-0 items-center gap-3',
  panelIconBox: 'flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-primary/[0.07] text-primary [&_svg]:h-5 [&_svg]:w-5',
  panelBody: 'min-w-0 p-6',
  textButton: 'rounded-full text-primary hover:bg-primary/10 hover:text-primary',
  dangerTextButton: 'rounded-full text-destructive hover:bg-destructive/5 hover:text-destructive',
  inlineEditor: 'space-y-3',
  textarea: 'min-h-[92px] w-full resize-none rounded-2xl border border-primary/15 bg-input-background px-4 py-3 text-sm leading-6 outline-none focus:border-primary',
  inlineEditorFooter: 'flex items-center justify-between text-xs text-muted-foreground [&>div]:flex [&>div]:gap-2',
  noticeBox: 'rounded-2xl border border-primary/10 bg-primary/[0.035] p-5 [&_p]:text-sm [&_p]:leading-6 [&_span]:mt-3 [&_span]:block [&_span]:text-xs [&_span]:text-muted-foreground',
  noticeInlineEditor: 'h-full min-h-0',
  noticeTextarea: 'h-full min-h-0',
  noticeEditActions: 'flex items-center gap-1',
  noticeEmptyState: 'flex h-full items-center justify-center rounded-2xl border border-dashed border-primary/15 bg-primary/[0.02] px-6 text-center [&_strong]:block [&_strong]:text-sm [&_p]:mt-1 [&_p]:text-xs [&_p]:text-muted-foreground',
  emptyState: 'flex min-h-[190px] flex-col items-center justify-center rounded-2xl border border-dashed border-primary/15 bg-primary/[0.02] px-6 text-center [&_strong]:mt-3 [&_strong]:text-sm [&_p]:mt-1 [&_p]:mb-4 [&_p]:text-xs [&_p]:text-muted-foreground',
  preservedEmptyState: 'h-full !min-h-0',
  noticePanelBody: 'flex h-[142px] flex-col [&>div]:min-h-0 [&>div]:flex-1',
  upcomingPanelBody: 'flex min-h-[285px] flex-col [&>div]:flex-1',
  emptyIconBox: 'flex h-11 w-11 items-center justify-center rounded-2xl bg-primary/[0.07] text-primary [&_svg]:h-5 [&_svg]:w-5',
  upcomingCard: 'space-y-5 rounded-2xl border border-primary/15 bg-gradient-to-br from-primary/[0.05] to-card p-5',
  upcomingMain: 'flex min-w-0 gap-5',
  scheduleDateBox: 'flex h-[84px] w-[84px] shrink-0 flex-col items-center justify-center rounded-[22px] bg-primary text-primary-foreground shadow-lg shadow-primary/20 [&_strong]:text-3xl [&_strong]:leading-none [&_span]:mt-1.5 [&_span]:text-xs',
  upcomingText: 'min-w-0 flex-1 [&_h3]:mt-2 [&_h3]:truncate [&_h3]:text-xl [&_h3]:font-medium',
  inlineBadges: 'flex flex-wrap items-center gap-2',
  statusBadge: (status: string) => `rounded-full border-transparent px-2.5 py-1 ${status === 'COMPLETED' ? 'bg-secondary text-muted-foreground' : status === 'CANCELLED' ? 'bg-destructive/10 text-destructive' : status === 'IN_PROGRESS' || status === 'TODAY' ? 'bg-emerald-100 text-emerald-700' : 'bg-primary/10 text-primary'}`,
  detailMeta: 'mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-muted-foreground [&_span]:flex [&_span]:items-center [&_span]:gap-1.5 [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:text-primary/70',
  deadlineText: 'mt-3 text-xs font-medium text-primary/75',
  scheduleActions: 'flex items-center justify-between gap-4 border-t border-primary/10 pt-4',
  voteButtons: 'flex flex-wrap items-center gap-2',
  voteButton: (active: boolean) => `h-9 rounded-full border px-4 text-xs font-medium transition-all ${active ? 'border-primary bg-primary text-primary-foreground shadow-sm shadow-primary/20' : 'border-primary/15 bg-background text-muted-foreground hover:bg-primary/5 hover:text-primary'}`,
  recentList: 'divide-y divide-primary/10',
  recentRow: 'flex w-full min-w-0 items-center gap-4 py-3 text-left transition-colors hover:text-primary',
  listIconBox: 'flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/[0.07] text-primary [&_svg]:h-4 [&_svg]:w-4',
  listMain: 'min-w-0 flex-1 [&_strong]:block [&_strong]:truncate [&_strong]:text-sm [&_span]:mt-1 [&_span]:block [&_span]:truncate [&_span]:text-xs [&_span]:text-muted-foreground',
  listMetric: 'w-16 shrink-0 text-center text-xs font-medium text-muted-foreground',
  summaryGrid: 'grid grid-cols-2 gap-3',
  summaryCard: 'rounded-2xl border border-primary/10 bg-primary/[0.025] p-4 [&>div]:flex [&>div]:items-center [&>div]:gap-2 [&_svg]:h-4 [&_svg]:w-4 [&_svg]:text-primary [&_span]:text-xs [&_span]:text-muted-foreground [&_strong]:mt-3 [&_strong]:block [&_strong]:text-lg [&_strong]:font-medium',
  chartSection: 'mt-5 border-t border-primary/10 pt-5',
  chartHeader: 'flex items-start justify-between gap-3 [&_strong]:block [&_strong]:text-base [&_span]:mt-1 [&_span]:block [&_span]:text-sm [&_span]:text-muted-foreground [&_em]:rounded-full [&_em]:bg-primary/10 [&_em]:px-2.5 [&_em]:py-1 [&_em]:text-xs [&_em]:font-medium [&_em]:not-italic [&_em]:text-primary',
  barChart: 'mt-5 grid h-[126px] grid-cols-4 gap-3 border-b border-primary/10 px-2',
  barChartColumn: 'flex min-h-0 flex-col items-center',
  barChartValue: 'mb-1 shrink-0 text-xs font-medium text-primary',
  barChartTrack: 'flex min-h-0 w-full flex-1 items-end justify-center [&_i]:max-h-full [&_i]:w-full [&_i]:max-w-9 [&_i]:rounded-t-xl [&_i]:bg-gradient-to-t [&_i]:from-primary [&_i]:to-primary/35 [&_i]:shadow-sm [&_i]:shadow-primary/10',
  barChartLabel: 'mt-2 shrink-0 text-xs text-muted-foreground',
  gradeChart: 'mt-5 grid grid-cols-2 gap-x-5 gap-y-3 border-t border-primary/10 pt-5 [&>div:first-child]:col-span-2 [&>div:not(:first-child)]:grid [&>div:not(:first-child)]:grid-cols-[32px_minmax(0,1fr)_28px] [&>div:not(:first-child)]:items-center [&>div:not(:first-child)]:gap-2 [&>div:not(:first-child)>span]:text-xs [&>div:not(:first-child)>span]:font-medium [&>div:not(:first-child)>i]:h-2 [&>div:not(:first-child)>i]:overflow-hidden [&>div:not(:first-child)>i]:rounded-full [&>div:not(:first-child)>i]:bg-secondary [&>div:not(:first-child)>i>b]:block [&>div:not(:first-child)>i>b]:h-full [&>div:not(:first-child)>i>b]:rounded-full [&>div:not(:first-child)>i>b]:bg-primary [&>div:not(:first-child)>em]:text-right [&>div:not(:first-child)>em]:text-xs [&>div:not(:first-child)>em]:not-italic [&>div:not(:first-child)>em]:text-muted-foreground',
  scheduleLayout: 'grid h-[calc(100dvh-22.5rem)] min-h-0 grid-cols-[minmax(0,1.25fr)_minmax(360px,0.75fr)] items-stretch gap-5',
  schedulePanel: 'flex h-full flex-col [&>div:last-child]:min-h-0 [&>div:last-child]:flex-1',
  calendarPanelBody: 'flex min-h-0 flex-col',
  scheduleSideBody: 'flex flex-col gap-4',
  calendarToolbar: 'mb-7 mt-2 flex items-center justify-center gap-5 [&_strong]:min-w-32 [&_strong]:text-center [&_strong]:text-lg [&_strong]:font-medium',
  iconButton: 'rounded-full hover:bg-primary/10 hover:text-primary',
  calendarLegend: 'mb-7 flex flex-wrap justify-center gap-4 text-xs text-muted-foreground [&_span]:flex [&_span]:items-center [&_span]:gap-1.5',
  legendDot: (status: string) => `h-2 w-2 rounded-full ${status === 'COMPLETED' ? 'bg-muted-foreground/40' : status === 'CANCELLED' ? 'bg-destructive' : status === 'IN_PROGRESS' ? 'bg-emerald-500' : 'bg-primary'}`,
  calendarWeek: 'mb-3 grid grid-cols-7 text-center text-sm font-medium text-muted-foreground [&_span:first-child]:text-rose-400 [&_span:last-child]:text-primary',
  calendarGrid: 'grid min-h-0 flex-1 auto-rows-fr grid-cols-7 gap-2',
  calendarDay: (selected: boolean, today: boolean) => `relative flex min-h-0 flex-col items-start rounded-2xl border p-2.5 text-base transition-all disabled:border-transparent disabled:bg-transparent ${selected ? 'border-primary bg-primary/[0.08] text-primary shadow-md shadow-primary/10' : today ? 'border-primary/30 bg-primary/[0.04] text-primary' : 'border-primary/10 bg-card hover:border-primary/30 hover:bg-primary/[0.03]'} [&>span]:flex [&>span]:w-full [&>span]:items-center [&>span]:justify-between [&>span]:font-medium [&>span_b]:flex [&>span_b]:h-8 [&>span_b]:w-8 [&>span_b]:items-center [&>span_b]:justify-center [&>span_b]:rounded-full [&>span_b]:bg-primary [&>span_b]:text-primary-foreground [&>span_small]:text-xs [&>span_small]:font-medium [&>span_small]:text-primary`,
  calendarEvent: (status: string) => `mt-auto w-full truncate rounded-lg px-2 py-1.5 text-left text-xs font-medium not-italic ${status === 'COMPLETED' ? 'bg-secondary text-muted-foreground' : status === 'CANCELLED' ? 'bg-destructive/10 text-destructive' : status === 'IN_PROGRESS' ? 'bg-emerald-100 text-emerald-700' : 'bg-primary/10 text-primary'}`,
  dayScheduleList: 'min-h-0 flex-1 space-y-3 overflow-y-auto pr-1',
  dayScheduleCard: 'relative flex w-full flex-col gap-2 rounded-2xl border border-primary/10 bg-primary/[0.025] p-5 text-left transition-all hover:border-primary/30 hover:bg-primary/[0.05] [&>strong]:mt-1 [&>strong]:text-base [&>span]:flex [&>span]:items-center [&>span]:gap-1.5 [&>span]:text-xs [&>span]:text-muted-foreground [&>span_svg]:h-3.5 [&>span_svg]:w-3.5',
  cardArrow: 'absolute right-5 top-1/2 -translate-y-1/2 text-muted-foreground [&_svg]:h-4 [&_svg]:w-4',
  monthScheduleSummary: 'mt-auto rounded-2xl border border-primary/10 bg-primary/[0.025] p-5 [&>div>strong]:block [&>div>strong]:text-base [&>div>span]:mt-1 [&>div>span]:block [&>div>span]:text-sm [&>div>span]:text-muted-foreground [&>section]:mt-4 [&>section]:grid [&>section]:grid-cols-3 [&>section]:gap-2 [&>section>span]:rounded-xl [&>section>span]:bg-card [&>section>span]:p-3 [&>section>span]:text-center [&>section>span]:text-xs [&>section>span]:text-muted-foreground [&>section>span>strong]:mb-1 [&>section>span>strong]:block [&>section>span>strong]:text-lg [&>section>span>strong]:text-foreground',
  toolbar: 'mb-5 flex min-w-0 items-center justify-between gap-4',
  searchBox: 'relative min-w-0 max-w-[440px] flex-1 [&>svg]:pointer-events-none [&>svg]:absolute [&>svg]:left-4 [&>svg]:top-1/2 [&>svg]:h-4 [&>svg]:w-4 [&>svg]:-translate-y-1/2 [&>svg]:text-muted-foreground',
  searchInput: 'h-10 rounded-full border-primary/10 bg-input-background pl-11',
  memberFilters: 'flex shrink-0 items-center gap-2',
  filterGroup: 'flex shrink-0 items-center gap-1 rounded-full bg-secondary/60 p-1',
  filterButton: (active: boolean) => `h-8 cursor-pointer rounded-full px-3 text-xs font-medium transition-all ${active ? 'bg-primary text-primary-foreground shadow-sm shadow-primary/20' : 'text-muted-foreground hover:bg-card hover:text-primary'}`,
  segmented: 'flex shrink-0 items-center gap-1 rounded-full bg-secondary/60 p-1',
  segmentButton: (active: boolean) => `h-8 rounded-full px-4 text-xs font-medium transition-all ${active ? 'bg-card text-primary shadow-sm' : 'text-muted-foreground hover:text-foreground'}`,
  boardList: 'min-h-0 flex-1 overflow-hidden divide-y divide-primary/10',
  boardRow: 'grid w-full grid-cols-[130px_minmax(0,1fr)_70px_70px_20px] items-center gap-3 py-4 text-left transition-colors hover:text-primary [&>svg]:h-4 [&>svg]:w-4',
  boardType: 'flex items-center gap-1.5 text-xs font-medium text-primary [&_svg]:h-3.5 [&_svg]:w-3.5',
  boardMetric: 'flex items-center justify-center gap-1.5 text-xs text-muted-foreground [&_svg]:h-3.5 [&_svg]:w-3.5',
  permissionGuide: 'mx-[-1.5rem] mt-auto flex h-[48px] shrink-0 items-center gap-2 bg-secondary/50 px-6 text-xs leading-none text-muted-foreground [&_svg]:h-4 [&_svg]:w-4 [&_svg]:text-primary',
  selectTrigger: 'h-10 w-40 rounded-full border-primary/10 bg-input-background',
  selectTriggerWide: 'h-11 rounded-xl border-primary/10 bg-input-background',
  guestSelectItem: 'cursor-pointer focus:bg-primary/10 focus:text-primary data-[highlighted]:bg-primary/10 data-[highlighted]:text-primary',
  memberGrid: 'grid min-h-0 flex-1 content-start grid-cols-3 gap-3',
  memberCard: 'rounded-2xl border border-primary/10 bg-primary/[0.02] p-4 text-left transition-all hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md hover:shadow-primary/5',
  memberTop: 'flex min-w-0 items-center gap-3 [&>svg]:h-4 [&>svg]:w-4 [&>svg]:shrink-0 [&>svg]:text-muted-foreground',
  avatar: 'flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-primary/10 text-sm font-medium text-primary',
  memberIdentity: 'min-w-0 flex-1 [&>div]:flex [&>div]:items-center [&>div]:gap-1.5 [&_strong]:truncate [&_strong]:text-base [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:text-primary [&>span]:mt-1 [&>span]:block [&>span]:text-sm [&>span]:text-muted-foreground',
  memberStats: 'mt-4 grid grid-cols-3 gap-2 border-t border-primary/10 pt-3 [&_span]:text-center [&_span]:text-xs [&_span]:text-muted-foreground [&_strong]:mb-1 [&_strong]:block [&_strong]:text-base [&_strong]:font-medium [&_strong]:text-foreground',
  requestList: 'space-y-3',
  requestCard: 'flex items-center gap-4 rounded-2xl border border-primary/10 bg-primary/[0.02] p-5',
  requestMain: 'min-w-0 flex-1 [&>div]:flex [&>div]:items-center [&>div]:gap-3 [&_strong]:text-sm [&>div_span]:text-xs [&>div_span]:text-muted-foreground [&_p]:mt-2 [&_p]:text-sm [&_p]:text-muted-foreground [&>span]:mt-2 [&>span]:block [&>span]:text-xs [&>span]:text-primary',
  requestActions: 'flex shrink-0 gap-2',
  requestBulkActions: 'flex items-center gap-2',
  historyList: 'divide-y divide-primary/10',
  historyRow: 'flex items-center gap-4 py-4 [&_time]:shrink-0 [&_time]:text-xs [&_time]:text-muted-foreground',
  pagination: 'flex shrink-0 items-center justify-center gap-1 pt-2',
  paginationArrow: 'flex h-9 w-9 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-primary/10 hover:text-primary disabled:pointer-events-none disabled:opacity-30 [&_svg]:h-4 [&_svg]:w-4',
  paginationPage: (active: boolean) => `flex h-9 min-w-9 items-center justify-center rounded-full px-3 text-xs font-medium transition-colors ${active ? 'bg-primary text-primary-foreground shadow-sm shadow-primary/20' : 'text-muted-foreground hover:bg-primary/10 hover:text-primary'}`,
  settingsGrid: 'grid grid-cols-1 items-start gap-5',
  settingsMain: 'min-w-0 space-y-5',
  settingsSide: 'min-w-0 space-y-5',
  settingsForm: 'space-y-4 [&_label]:block [&_label>span]:mb-2 [&_label>span]:block [&_label>span]:text-sm [&_label>span]:font-medium',
  input: 'h-11 rounded-xl border-primary/10 bg-input-background',
  saveButton: 'ml-auto flex h-10 rounded-full px-5 shadow-md shadow-primary/15 hover:bg-primary/90 hover:text-primary-foreground',
  switchList: 'space-y-2',
  settingSwitch: 'flex items-center justify-between gap-5 py-4 first:pt-0 last:pb-0 [&>div]:min-w-0 [&_strong]:block [&_strong]:text-sm [&_span]:mt-1 [&_span]:block [&_span]:text-xs [&_span]:text-muted-foreground',
  settingsTwoColumns: 'mt-5 grid grid-cols-2 gap-4 border-t border-primary/10 pt-5 [&_label>span]:mb-2 [&_label>span]:block [&_label>span]:text-sm [&_label>span]:font-medium',
  managerRow: 'flex items-center gap-4 rounded-2xl border border-primary/10 bg-primary/[0.02] p-4',
  protectedAction: 'mt-4 flex items-center justify-between gap-4 rounded-2xl border border-primary/10 p-4 [&_strong]:block [&_strong]:text-sm [&_span]:mt-1 [&_span]:block [&_span]:text-xs [&_span]:text-muted-foreground',
  imageSetting: 'flex min-h-[190px] flex-col items-center justify-center text-center [&_img]:h-32 [&_img]:w-32 [&_img]:shrink-0 [&_img]:rounded-[28px] [&_img]:object-cover [&_img]:shadow-md [&>div]:mt-5 [&>div]:flex [&>div]:gap-2',
  dangerZone: 'flex min-h-[130px] items-center gap-6 rounded-2xl border border-destructive/15 bg-destructive/[0.025] p-6 [&_strong]:shrink-0 [&_strong]:text-sm [&_p]:min-w-0 [&_p]:flex-1 [&_p]:text-xs [&_p]:leading-5 [&_p]:text-muted-foreground [&_button]:shrink-0',
  modalOverlay: 'fixed inset-0 z-50 flex items-center justify-center bg-foreground/20 p-6 backdrop-blur-sm',
  modal: 'max-h-[92vh] w-full max-w-[720px] rounded-[28px] border border-primary/15 bg-card shadow-2xl shadow-primary/15',
  scheduleModal: 'flex h-[740px] flex-col [&>header]:shrink-0',
  modalHeader: 'flex items-center justify-between border-b border-primary/10 px-6 py-5 [&_h2]:text-xl [&_h2]:font-medium',
  modalHeaderWithBack: 'grid grid-cols-[36px_minmax(0,1fr)_36px] items-center border-b border-primary/10 px-6 py-5 [&_h2]:text-center [&_h2]:text-xl [&_h2]:font-medium',
  modalBody: 'max-h-[calc(88vh-74px)] overflow-y-auto p-6',
  scheduleModalBody: 'min-h-0 w-full flex-1 p-6',
  modalStack: 'w-full space-y-5',
  scheduleModalContent: 'flex h-full min-h-0 w-full flex-col gap-4 [&>div:last-child]:mt-auto',
  writePostModalContent: 'flex h-full min-h-0 w-full flex-col gap-5 overflow-y-auto pb-1 pr-1 [&>div:last-child]:mt-auto',
  postModalContent: 'flex h-full min-h-0 w-full flex-col gap-5',
  participantsModalContent: 'flex h-full min-h-0 w-full flex-col gap-5',
  secondaryScheduleModalContent: 'flex h-full min-h-0 w-full flex-col gap-10 [&>div:last-child]:mt-auto',
  modalHighlight: 'flex flex-col items-start gap-2 rounded-2xl border border-primary/10 bg-primary/[0.03] p-5 [&_strong]:text-lg [&_span]:flex [&_span]:items-center [&_span]:gap-1.5 [&_span]:text-sm [&_span]:text-muted-foreground [&_svg]:h-4 [&_svg]:w-4',
  modalStats: 'grid grid-cols-4 gap-3 [&_span]:rounded-2xl [&_span]:bg-secondary/50 [&_span]:p-4 [&_span]:text-center [&_span]:text-xs [&_span]:text-muted-foreground [&_strong]:mb-1 [&_strong]:block [&_strong]:text-lg [&_strong]:font-medium [&_strong]:text-foreground',
  modalSection: 'rounded-2xl border border-primary/10 p-5 [&_h3]:text-sm [&_h3]:font-medium [&_p]:mt-1 [&_p]:mb-4 [&_p]:text-xs [&_p]:text-muted-foreground',
  modalActions: 'flex justify-end gap-2 border-t border-primary/10 pt-5',
  postMetaRow: 'flex min-h-9 shrink-0 items-center justify-between gap-4',
  postMeta: 'flex min-h-9 flex-wrap items-center gap-3 text-xs text-muted-foreground [&_[data-slot=badge]]:inline-flex [&_[data-slot=badge]]:h-7 [&_[data-slot=badge]]:items-center [&_span]:flex [&_span]:items-center [&_span]:gap-1 [&_svg]:h-3.5 [&_svg]:w-3.5',
  postActions: 'flex shrink-0 items-center gap-1',
  postContent: 'min-h-[120px] rounded-2xl bg-secondary/35 p-5 text-sm leading-7',
  postEditArea: 'space-y-3',
  postEditTextarea: 'min-h-[120px] w-full resize-none rounded-2xl border border-primary/15 bg-input-background p-5 text-sm leading-7 outline-none focus:border-primary',
  postEditActions: 'flex justify-end gap-2',
  postComments: 'flex min-h-0 flex-1 flex-col rounded-2xl border border-primary/10 p-5 [&>h3]:mb-4 [&>h3]:shrink-0 [&>h3]:text-sm [&>h3]:font-medium',
  commentList: 'min-h-0 flex-1 space-y-3 overflow-y-auto pr-1',
  commentThread: 'space-y-2',
  comment: 'flex gap-3 rounded-xl bg-secondary/35 p-4',
  commentReply: 'ml-10 flex gap-3 rounded-xl border-l-2 border-primary/20 bg-primary/[0.025] p-4',
  commentBody: 'min-w-0 flex-1 [&>p]:mt-2 [&>p]:mb-1 [&>p]:text-sm [&>small]:text-[10px] [&>small]:text-muted-foreground',
  commentHeader: 'flex items-center justify-between gap-3 [&>strong]:text-xs [&>span]:flex [&>span]:gap-2 [&>span>button]:text-[10px] [&>span>button]:text-muted-foreground [&>span>button:hover]:text-primary',
  commentEdit: 'mt-2 flex items-center gap-2',
  replyInput: 'mt-3 flex items-center gap-2',
  avatarSmall: 'flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-xs text-primary',
  commentInput: 'mt-4 flex gap-2',
  modalField: 'block [&>span]:mb-2 [&>span]:block [&>span]:text-sm [&>span]:font-medium',
  timeFieldRow: 'grid grid-cols-2 gap-3',
  modalTextarea: 'min-h-[180px] w-full resize-none rounded-2xl border border-primary/15 bg-input-background px-4 py-3 text-sm leading-6 outline-none focus:border-primary',
  postFileUpload: 'block rounded-2xl border border-dashed border-primary/20 bg-primary/[0.025] p-4 [&>span]:mb-3 [&>span]:flex [&>span]:items-center [&>span]:gap-2 [&>span]:text-sm [&>span]:font-medium [&>span>svg]:h-4 [&>span>svg]:w-4 [&>span>svg]:text-primary [&>small]:mt-2 [&>small]:block [&>small]:text-xs [&>small]:text-muted-foreground',
  postFileList: 'mt-3 max-h-16 space-y-1 overflow-y-auto text-xs text-muted-foreground [&>li]:flex [&>li]:items-center [&>li]:gap-2 [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:shrink-0 [&_svg]:text-primary',
  postPinOption: (active: boolean) => `flex w-full cursor-pointer items-center justify-between rounded-2xl border px-4 py-3 text-left transition-colors ${active ? 'border-primary/25 bg-primary/[0.07]' : 'border-primary/10 bg-card hover:border-primary/20 hover:bg-primary/[0.035]'} [&>span]:flex [&>span]:items-center [&>span]:gap-3 [&>span:first-child>svg]:h-4 [&>span:first-child>svg]:w-4 [&>span:first-child>svg]:text-primary [&>span:first-child>span>strong]:block [&>span:first-child>span>strong]:text-sm [&>span:first-child>span>small]:mt-1 [&>span:first-child>span>small]:block [&>span:first-child>span>small]:text-xs [&>span:first-child>span>small]:text-muted-foreground [&>span:last-child]:shrink-0 [&>span:last-child]:rounded-full [&>span:last-child]:px-3 [&>span:last-child]:py-1.5 [&>span:last-child]:text-xs [&>span:last-child]:font-medium ${active ? '[&>span:last-child]:bg-primary [&>span:last-child]:text-primary-foreground' : '[&>span:last-child]:bg-secondary [&>span:last-child]:text-muted-foreground'} [&>span:last-child>svg]:h-3.5 [&>span:last-child>svg]:w-3.5`,
  participantSummary: 'rounded-2xl border border-primary/15 bg-gradient-to-br from-primary/[0.08] to-card p-5 [&>div:first-child]:flex [&>div:first-child]:items-center [&>div:first-child]:gap-3 [&>div:first-child>svg]:h-5 [&>div:first-child>svg]:w-5 [&>div:first-child>svg]:text-primary [&>div:first-child>span]:text-xs [&>div:first-child>span]:text-muted-foreground [&>div:first-child>span>strong]:mr-2 [&>div:first-child>span>strong]:text-lg [&>div:first-child>span>strong]:text-foreground',
  participantSummaryStats: 'mt-4 grid grid-cols-3 gap-2',
  participantFilter: (active: boolean) => `cursor-pointer rounded-xl p-3 text-center text-xs transition-all [&>strong]:mb-1 [&>strong]:block [&>strong]:text-lg ${active ? 'bg-primary text-primary-foreground shadow-sm shadow-primary/20' : 'bg-card/80 text-muted-foreground hover:bg-primary/10 hover:text-primary [&>strong]:text-foreground'}`,
  participantSectionTitle: 'flex items-center justify-between px-1 [&>strong]:text-sm [&>span]:rounded-full [&>span]:bg-primary/10 [&>span]:px-2.5 [&>span]:py-1 [&>span]:text-xs [&>span]:font-medium [&>span]:text-primary',
  participantList: 'grid max-h-[348px] min-h-0 grid-cols-2 content-start gap-3 overflow-y-auto pr-1',
  participantCard: 'flex min-w-0 items-center gap-3 rounded-2xl border border-primary/10 bg-primary/[0.02] p-4 [&>span]:min-w-0 [&>span]:flex-1 [&>span>strong]:block [&>span>strong]:truncate [&>span>strong]:text-sm [&>span>small]:mt-1 [&>span>small]:block [&>span>small]:truncate [&>span>small]:text-xs [&>span>small]:text-muted-foreground',
  participantAvatar: 'flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-primary/10 text-sm font-medium text-primary',
  guestAvatar: 'flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-secondary text-sm font-medium text-muted-foreground',
  participantProfileImage: 'h-11 w-11 shrink-0 rounded-2xl object-cover',
  participantBadges: 'flex shrink-0 items-center gap-2.5',
  guestBadge: 'text-muted-foreground',
  participantRoleBadge: 'text-muted-foreground',
  imageUpload: 'block rounded-2xl border border-dashed border-primary/20 bg-primary/[0.025] p-5 [&>span]:mb-3 [&>span]:block [&>span]:text-sm [&>span]:font-medium',
  memberModalHeader: 'flex items-center gap-4 rounded-2xl bg-primary/[0.03] p-5 [&>div:last-child>div]:flex [&>div:last-child>div]:items-center [&>div:last-child>div]:gap-2 [&_h3]:text-xl [&_h3]:font-medium [&_p]:mt-1 [&_p]:text-sm [&_p]:text-muted-foreground',
  avatarLarge: 'flex h-16 w-16 shrink-0 items-center justify-center rounded-[22px] bg-primary/10 text-xl font-medium text-primary',
  memberModalContent: 'flex h-full min-h-0 w-full flex-col gap-5 [&>div:last-child]:mt-auto',
  memberModalScroll: 'min-h-0 flex-1 space-y-5 overflow-y-auto pr-1',
  memberManagementModal: 'flex h-full min-h-0 w-full flex-col gap-5 [&>div:last-child]:mt-auto',
  memberManagementScroll: 'min-h-0 flex-1 space-y-5 overflow-y-auto pr-1',
  memberDetailGrid: 'grid grid-cols-3 gap-3 [&_span]:rounded-2xl [&_span]:border [&_span]:border-primary/10 [&_span]:p-4 [&_span]:text-center [&_span]:text-sm [&_span]:text-muted-foreground [&_strong]:mb-1 [&_strong]:block [&_strong]:text-xl [&_strong]:font-medium [&_strong]:text-foreground',
  memberMemo: 'min-h-[132px] rounded-2xl border border-primary/10 bg-primary/[0.025] p-5 [&>div:first-child]:flex [&>div:first-child]:items-center [&>div:first-child]:gap-2 [&>div:first-child>svg]:h-4 [&>div:first-child>svg]:w-4 [&>div:first-child>svg]:text-primary [&>div:first-child>strong]:text-sm [&>div:first-child>button]:ml-auto [&>p]:mt-3 [&>p]:text-sm [&>p]:text-muted-foreground',
  memberMemoHeaderActions: 'ml-auto flex items-center gap-1 [&>button]:!ml-0',
  memberMemoInlineTextarea: 'mt-3 h-16 w-full resize-none rounded-xl border border-primary/10 bg-input-background px-4 py-3 text-sm outline-none focus:border-primary',
  roleSelector: 'grid grid-cols-2 gap-3',
  roleOption: (active: boolean) => `flex cursor-pointer items-center gap-3 rounded-2xl border p-5 text-left transition-colors ${active ? 'border-primary/30 bg-primary/[0.07]' : 'border-primary/10 hover:border-primary/25 hover:bg-primary/[0.03]'} [&>svg]:h-5 [&>svg]:w-5 [&>svg]:shrink-0 [&>svg]:text-primary [&_strong]:block [&_strong]:text-sm [&_small]:mt-1 [&_small]:block [&_small]:text-xs [&_small]:text-muted-foreground`,
  permissionSection: 'rounded-2xl border border-primary/10 p-5 [&>strong]:mb-3 [&>strong]:block [&>strong]:text-sm',
  permissionOptionList: 'space-y-2',
  permissionOption: (active: boolean) => `flex w-full cursor-pointer items-center justify-between rounded-xl border px-4 py-3 text-left transition-colors disabled:cursor-not-allowed disabled:opacity-50 ${active ? 'border-primary/25 bg-primary/[0.07]' : 'border-primary/10 bg-card hover:border-primary/20 hover:bg-primary/[0.035]'} [&>span:first-child>strong]:block [&>span:first-child>strong]:text-sm [&>span:first-child>small]:mt-1 [&>span:first-child>small]:block [&>span:first-child>small]:text-xs [&>span:first-child>small]:text-muted-foreground [&>span:last-child]:flex [&>span:last-child]:shrink-0 [&>span:last-child]:items-center [&>span:last-child]:gap-1.5 [&>span:last-child]:rounded-full [&>span:last-child]:px-3 [&>span:last-child]:py-1.5 [&>span:last-child]:text-xs [&>span:last-child]:font-medium ${active ? '[&>span:last-child]:bg-primary [&>span:last-child]:text-primary-foreground' : '[&>span:last-child]:bg-secondary [&>span:last-child]:text-muted-foreground'} [&>span:last-child>svg]:h-3.5 [&>span:last-child>svg]:w-3.5`,
  ownershipSummary: 'flex items-center gap-4 rounded-2xl border border-primary/15 bg-primary/[0.04] p-6 [&>svg]:h-7 [&>svg]:w-7 [&>svg]:shrink-0 [&>svg]:text-primary [&_strong]:block [&_strong]:text-lg [&_span]:mt-2 [&_span]:block [&_span]:text-sm [&_span]:text-muted-foreground',
  ownershipChanges: 'space-y-3 rounded-2xl border border-primary/10 p-5 [&>strong]:mb-4 [&>strong]:block [&>strong]:text-sm [&>span]:flex [&>span]:items-center [&>span]:gap-2 [&>span]:text-sm [&>span]:text-muted-foreground [&_svg]:h-4 [&_svg]:w-4 [&_svg]:text-primary',
  removalSummary: 'flex items-center gap-4 rounded-2xl border border-destructive/15 bg-destructive/[0.035] p-6 [&>svg]:h-7 [&>svg]:w-7 [&>svg]:shrink-0 [&>svg]:text-destructive [&_strong]:block [&_strong]:text-lg [&_span]:mt-2 [&_span]:block [&_span]:text-sm [&_span]:text-muted-foreground',
  groupDeletionScheduleWarning: 'rounded-2xl border border-amber-200 bg-amber-50/70 p-5 [&>div]:flex [&>div]:items-center [&>div]:gap-3 [&_svg]:h-5 [&_svg]:w-5 [&_svg]:shrink-0 [&_svg]:text-amber-600 [&_strong]:block [&_strong]:text-sm [&_small]:mt-1 [&_small]:block [&_small]:text-xs [&_small]:text-amber-700/80 [&_p]:mt-3 [&_p]:text-xs [&_p]:leading-5 [&_p]:text-muted-foreground',
  confirmContent: 'flex flex-col items-center text-center [&>p]:mt-4 [&>p]:max-w-md [&>p]:text-sm [&>p]:leading-6 [&>p]:text-muted-foreground [&_.modal-actions]:mt-5',
  warningIconBox: 'flex h-14 w-14 items-center justify-center rounded-2xl bg-destructive/10 text-destructive [&_svg]:h-6 [&_svg]:w-6',
  floatingNotice: 'fixed bottom-7 left-[calc(50%+8rem)] z-[60] -translate-x-1/2 rounded-full border border-primary/15 bg-card px-5 py-3 text-sm font-medium shadow-xl shadow-primary/10',
} as const;
