export const styles = {
  page: 'min-h-screen bg-background',
  header: 'border-b border-border bg-card',
  headerInner: 'max-w-5xl mx-auto px-6 py-4 flex items-center justify-between',
  row: 'flex items-center gap-6',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  content: 'max-w-5xl mx-auto px-6 py-8',
  sectionHeader: 'mb-6',
  row2: 'flex items-center gap-3 mb-2',
  settingsIcon: 'w-8 h-8 text-primary',
  pageTitle: 'text-4xl font-medium',
  descriptionText: 'text-muted-foreground',
  form: 'space-y-8',
  contentBox: 'rounded-xl border border-primary/30 bg-primary/5 p-3 text-center text-sm text-primary',
  header2: 'bg-card border border-border rounded-3xl p-8 space-y-6',
  row3: 'flex items-center gap-3 pb-4 border-b border-border',
  usersIcon: 'w-5 h-5 text-primary',
  sectionTitle: 'text-2xl font-medium',
  stack: 'space-y-4',
  stack2: 'space-y-2',
  input: 'rounded-xl',
  textareaIcon: 'min-h-24 rounded-xl',
  descriptionText2: 'text-sm text-muted-foreground',
  betweenRow: 'flex items-center justify-between',
  row4: 'flex-1',
  summaryText: 'font-medium',
  cardGrid: 'grid md:grid-cols-2 gap-4',
  statsGrid: 'grid md:grid-cols-3 gap-4',
  betweenRow2: 'flex items-center justify-between rounded-2xl border border-border p-5',
  row5: 'flex gap-3',
  fullWidthButton: 'w-full rounded-full',
  submitButton: 'flex-1 rounded-full',
  contentBox2: 'bg-destructive/10 border-2 border-destructive/30 rounded-3xl p-8',
  mediaRow: 'flex items-start gap-6',
  row6: 'w-16 h-16 rounded-2xl bg-destructive/20 flex items-center justify-center flex-shrink-0',
  trash2Icon: 'w-8 h-8 text-destructive',
  cardTitle: 'text-xl font-medium mb-2 text-destructive',
  descriptionText3: 'text-muted-foreground mb-4',
  roundButton: 'rounded-full gap-2',
} as const;
