export const styles = {
  page: 'min-h-screen bg-background',
  header: 'border-b border-border bg-card px-4 py-4',
  logoWrapper: 'justify-center',
  content: 'max-w-2xl mx-auto px-4 py-12 space-y-8',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  stack: 'text-center space-y-4',
  row: 'w-20 h-20 rounded-full bg-gradient-to-br from-primary/20 to-primary/5 mx-auto flex items-center justify-center mb-4',
  userPlusIcon: 'w-10 h-10 text-primary',
  pageTitle: 'text-4xl font-medium mb-3',
  descriptionText: 'text-lg text-muted-foreground',
  header2: 'bg-card border border-border rounded-3xl p-8 md:p-10 shadow-sm',
  form: 'space-y-8',
  sectionTitle: 'text-xl font-medium mb-6 flex items-center gap-3',
  row2: 'w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center',
  userIcon: 'w-4 h-4 text-primary',
  stack2: 'space-y-6',
  stack3: 'space-y-2',
  input: 'rounded-xl h-12',
  cardGrid: 'grid grid-cols-2 gap-4',
  footerActions: 'border-t border-border pt-8',
  descriptionText2: 'text-sm text-muted-foreground',
  summaryBox: 'bg-secondary/30 rounded-2xl p-6',
  cardTitle: 'font-medium mb-3',
  list: 'space-y-2 text-sm text-muted-foreground',
  listItem: 'flex items-start gap-2',
  row3: 'w-1.5 h-1.5 rounded-full bg-primary mt-1.5 flex-shrink-0',
  footerActions2: 'border-t border-border pt-8 space-y-4',
  submitButton: 'w-full rounded-full h-12 shadow-lg shadow-primary/20',
  userPlusIcon2: 'w-5 h-5 mr-2',
  cardLink: 'block',
  fullWidthButton: 'w-full rounded-full h-12',
  contentBox: 'bg-gradient-to-br from-secondary/50 to-transparent rounded-2xl p-8 text-center border border-border',
  cardTitle2: 'font-medium mb-2',
  descriptionText3: 'text-sm text-muted-foreground mb-6',
  roundButton: 'rounded-full gap-2',
} as const;
