export const styles = {
  page: 'relative flex min-h-screen items-center justify-center overflow-x-hidden bg-background px-4 py-4',
  backgroundGlowTop: 'pointer-events-none absolute right-0 top-0 h-80 w-80 rounded-full bg-primary/5 blur-3xl',
  backgroundGlowBottom: 'pointer-events-none absolute bottom-0 left-0 h-96 w-96 rounded-full bg-primary/5 blur-3xl',
  header: 'hidden',
  headerInner: 'flex w-full items-center justify-between px-4 py-2 md:px-8 md:py-4',
  headerActions: 'flex gap-2',
  headerButton: 'cursor-pointer rounded-full px-4 text-muted-foreground hover:bg-primary/10 hover:text-primary md:px-5',
  headerPrimaryButton: 'cursor-pointer rounded-full bg-indigo-600 px-4 text-white shadow-sm shadow-indigo-600/20 hover:bg-indigo-700 hover:shadow-md hover:shadow-indigo-600/25 md:px-5',
  logInIcon: 'w-4 h-4 mr-2',
  profileMenuWrapper: 'relative',
  profileButton: 'flex cursor-pointer items-center gap-1.5 border-0 bg-transparent p-0 text-sm font-medium text-muted-foreground transition-colors hover:text-primary',
  profileName: 'max-w-32 truncate md:max-w-40',
  chevronDownIcon: (open: boolean) => [
    'h-4 w-4 text-muted-foreground transition-transform',
    open ? 'rotate-180 text-primary' : '',
  ].join(' '),
  profileDropdown: 'absolute right-0 top-[calc(100%+0.75rem)] z-50 w-64 overflow-hidden rounded-3xl border border-border bg-card p-2 shadow-2xl shadow-primary/10',
  profileSummary: 'flex items-center gap-3 rounded-2xl bg-primary/5 p-3',
  profileSummaryAvatar: 'flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary text-sm font-semibold text-primary-foreground',
  profileSummaryText: 'min-w-0 flex-1',
  profileSummaryName: 'block truncate text-sm font-semibold text-foreground',
  profileSummaryEmail: 'block truncate text-xs text-muted-foreground',
  menuDivider: 'my-2 h-px bg-border',
  profileMenuItem: 'flex w-full cursor-pointer items-center gap-3 rounded-2xl px-3 py-2.5 text-left text-sm font-medium text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground',
  logoutMenuItem: 'flex w-full cursor-pointer items-center gap-3 rounded-2xl px-3 py-2.5 text-left text-sm font-medium text-muted-foreground transition-colors hover:bg-destructive/10 hover:text-destructive',
  profileMenuIcon: 'h-4 w-4',
  content: 'relative z-10 mx-auto flex w-full max-w-2xl flex-col items-center justify-center gap-3 md:gap-4',
  logo: 'mx-auto',
  loadingBox: 'bg-card border border-border rounded-3xl p-10 text-center text-muted-foreground shadow-sm',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  stack: 'space-y-4 pt-3 text-center',
  row: 'w-20 h-20 rounded-full bg-gradient-to-br from-primary/20 to-primary/5 mx-auto flex items-center justify-center mb-4',
  userPlusIcon: 'w-10 h-10 text-primary',
  pageTitle: 'text-2xl font-medium md:text-3xl',
  descriptionText: 'text-sm text-muted-foreground md:text-base',
  header2: 'bg-card border border-border rounded-3xl p-8 md:p-10 shadow-sm',
  form: 'space-y-8',
  authChoice: 'rounded-2xl border border-primary/10 bg-primary/5 p-5 text-center space-y-4',
  authChoiceText: 'text-sm leading-6 text-muted-foreground',
  authChoiceActions: 'flex justify-center gap-3',
  sessionCard: 'rounded-2xl border border-border bg-secondary/20 p-6 space-y-5',
  sessionHeader: 'flex items-start justify-between gap-4',
  groupName: 'text-sm text-primary font-medium',
  sessionTitle: 'text-2xl font-medium text-foreground mt-1',
  statusBadge: 'inline-flex items-center rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary',
  sessionMeta: 'flex flex-wrap gap-x-8 gap-y-3 text-sm text-muted-foreground [&>span]:flex [&>span]:items-center [&>span]:gap-1.5',
  metaIcon: 'h-4 w-4 shrink-0 text-primary',
  voteSummary: 'grid grid-cols-3 gap-3 border-t border-border pt-4 text-center text-sm text-muted-foreground [&_strong]:block [&_strong]:text-lg [&_strong]:text-foreground',
  sectionTitle: 'text-xl font-medium mb-6 flex items-center gap-3',
  row2: 'w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center',
  userIcon: 'w-4 h-4 text-primary',
  stack2: 'space-y-6',
  stack3: 'space-y-2',
  input: 'h-11 rounded-xl bg-input-background [&:not(:placeholder-shown)]:bg-input-background [&:-webkit-autofill]:[-webkit-text-fill-color:var(--foreground)] [&:-webkit-autofill]:[box-shadow:0_0_0_1000px_var(--input-background)_inset] [&:-webkit-autofill:focus]:[box-shadow:0_0_0_1000px_var(--input-background)_inset]',
  selectItem: 'cursor-pointer focus:bg-primary/10 focus:text-primary data-[highlighted]:bg-primary/10 data-[highlighted]:text-primary',
  cardGrid: 'grid grid-cols-2 gap-4',
  profileBox: 'rounded-2xl border border-border bg-secondary/20 p-5 text-sm text-foreground',
  voteGrid: 'grid grid-cols-3 gap-3',
  voteButton: (active: boolean) => `rounded-2xl border px-4 py-4 text-left transition-all ${active ? 'border-primary bg-primary text-primary-foreground shadow-lg shadow-primary/20' : 'border-border bg-card text-foreground hover:border-primary/40 hover:bg-primary/5'} [&_strong]:block [&_span]:mt-1 [&_span]:block [&_span]:text-xs ${active ? '[&_span]:text-primary-foreground/80' : '[&_span]:text-muted-foreground'}`,
  footerActions: 'border-t border-border pt-8',
  descriptionText2: 'mt-4 text-sm text-muted-foreground',
  successText: 'rounded-2xl bg-primary/10 px-4 py-3 text-sm text-primary',
  errorText: 'rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-500',
  summaryBox: 'bg-secondary/30 rounded-2xl p-6',
  cardTitle: 'font-medium mb-3',
  list: 'space-y-2 text-sm text-muted-foreground',
  listItem: 'flex items-start gap-2',
  row3: 'w-1.5 h-1.5 rounded-full bg-primary mt-1.5 flex-shrink-0',
  footerActions2: 'border-t border-border pt-8 space-y-4',
  submitButton: 'w-full rounded-full h-12 shadow-lg shadow-primary/20',
  userPlusIcon2: 'w-5 h-5 mr-2',
  cardLink: 'block',
  fullWidthButton: 'w-full rounded-full h-12',
  contentBox: 'bg-gradient-to-br from-secondary/50 to-transparent rounded-2xl p-8 text-center border border-border',
  cardTitle2: 'font-medium mb-2',
  descriptionText3: 'text-sm text-muted-foreground mb-6',
  roundButton: 'rounded-full gap-2',
  completionCard: 'flex min-h-[520px] flex-col items-center justify-center gap-6 rounded-3xl border border-border bg-card p-8 text-center shadow-sm',
  completionIcon: 'mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary/10',
  completionIconSvg: 'h-9 w-9 text-primary',
  completionTitle: 'text-3xl font-medium',
  completionText: 'text-sm text-muted-foreground',
} as const;
