export const styles = {
  page: 'min-h-screen bg-background flex flex-col',
  header: 'border-b border-border bg-card px-4 py-4',
  logoWrapper: 'justify-center',
  row: 'flex-1 px-4 py-6 md:py-12',
  content: 'w-full max-w-2xl mx-auto space-y-6',
  stack: 'text-center space-y-4 pt-2',
  row2: 'w-24 h-24 rounded-full bg-gradient-to-br from-accent/30 to-accent/10 mx-auto flex items-center justify-center mb-4',
  qrCodeIcon: 'w-12 h-12 text-accent-foreground',
  pageTitle: 'text-4xl font-medium mb-3',
  descriptionText: 'text-lg text-muted-foreground',
  header2: 'bg-card border-2 border-border rounded-3xl p-5 md:p-8 shadow-lg',
  grid: 'grid gap-3 mb-6',
  row3: 'flex items-center gap-3 p-4 bg-secondary/30 rounded-xl',
  calendarIcon: 'w-5 h-5 text-primary flex-shrink-0',
  textContent: 'min-w-0',
  descriptionText2: 'text-xs text-muted-foreground',
  summaryText: 'font-medium truncate',
  stack2: 'space-y-3',
  cardLink: 'block',
  contentBox: 'bg-primary text-primary-foreground border-2 border-primary rounded-2xl p-6 hover:shadow-lg transition-all group cursor-pointer',
  row4: 'flex items-center gap-4',
  row5: 'w-14 h-14 rounded-xl bg-primary-foreground/20 flex items-center justify-center',
  userCheckIcon: 'w-7 h-7 text-primary-foreground',
  row6: 'flex-1',
  summaryText2: 'text-2xl font-medium mb-1',
  paragraphText: 'text-sm opacity-90',
  badge: 'bg-primary-foreground text-primary',
  header3: 'bg-card border-2 border-border rounded-2xl p-6 hover:border-primary transition-all group cursor-pointer',
  row7: 'w-12 h-12 rounded-xl bg-secondary flex items-center justify-center group-hover:scale-110 transition-transform',
  userPlusIcon: 'w-6 h-6 text-primary',
  summaryText3: 'text-xl font-medium mb-1',
  descriptionText3: 'text-sm text-muted-foreground',
  centeredBlock: 'text-center',
  descriptionText4: 'text-muted-foreground',
  primaryLink: 'text-primary hover:underline font-medium',
} as const;
