import { FormEvent, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Clock } from 'lucide-react';
import { SessionFlowIcon, SessionFlowPage } from '../components/SessionFlowLayout';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { sessionEntryApi } from '../utils/sessionEntryApi';
import { ApiClientError } from '../utils/apiClient';
import { setAuthRedirectPath } from '../utils/authSession';

export default function LateRegistrationPage() {
  const id = Number(useParams().sessionId); const navigate = useNavigate(); const [minutes, setMinutes] = useState('10'); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); const lateMinutes = Number(minutes); if (!Number.isInteger(lateMinutes) || lateMinutes < 1 || lateMinutes > 180) { setError('1분에서 180분 사이로 입력해 주세요.'); return; } setBusy(true); try { const next = await sessionEntryApi.attendance(id, { status: 'LATE', lateMinutes, reason }); if (next.restrictionReason) { navigate(`/sessions/${id}/entry-result/${next.restrictionReason.toLowerCase().replaceAll('_', '-')}`, { state: { entry: next } }); return; } navigate(`/sessions/${id}/entry-result/late-complete`, { state: { entry: next } }); } catch (errorValue) { if (errorValue instanceof ApiClientError && errorValue.status === 401) { const path = `/sessions/${id}/late`; setAuthRedirectPath(path); navigate(`/login?redirect=${encodeURIComponent(path)}`); } else if (errorValue instanceof ApiClientError && errorValue.status === 403) setError('참가자 정보를 찾지 못했어요. 일정 입장 화면에서 다시 확인해 주세요.'); else setError('지각 정보를 저장하지 못했어요.'); } finally { setBusy(false); } };
  return <SessionFlowPage><form onSubmit={submit}><div className="text-center"><SessionFlowIcon><Clock className="h-9 w-9" /></SessionFlowIcon><h1 className="mt-4 text-[1.65rem] font-bold md:text-4xl">조금 늦어요</h1><p className="mt-2 text-sm text-muted-foreground">예상 지각 시간을 알려주세요.</p></div><label className="mt-4 block font-bold" htmlFor="late-minutes">몇 분 정도 늦나요?</label><div className="relative mt-2"><Input id="late-minutes" type="number" min="1" max="180" value={minutes} onChange={e => setMinutes(e.target.value)} className="h-14 rounded-2xl pr-14 text-lg"/><span className="absolute right-5 top-4 text-muted-foreground">분</span></div><label className="mt-3 block font-bold" htmlFor="late-reason">이유 <span className="font-normal text-muted-foreground">(선택)</span></label><Input id="late-reason" value={reason} maxLength={300} onChange={e => setReason(e.target.value)} placeholder="예: 교통이 막혀요" className="mt-2 h-14 rounded-2xl"/><p className="min-h-8 pt-2 text-center text-sm text-destructive">{error}</p><Button type="submit" disabled={busy} className="h-14 w-full rounded-2xl text-[17px] font-bold">도착 예정 알리기</Button>{error.includes('참가자 정보') && <Button type="button" variant="outline" className="mt-2 h-14 w-full rounded-2xl hover:bg-secondary hover:text-foreground" onClick={() => navigate('/session-entry')}>일정 입장으로 이동</Button>}</form></SessionFlowPage>;
}
