export const styles = {
  page: 'min-h-screen bg-gradient-to-b from-background to-secondary/20',
  emptyState: 'px-4 py-6',
  logoWrapper: 'justify-center',
  content: 'max-w-md mx-auto px-4 pb-12 space-y-8',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  stack: 'text-center space-y-3',
  row: 'w-20 h-20 rounded-full bg-secondary mx-auto flex items-center justify-center mb-4',
  clockIcon: 'w-10 h-10 text-primary',
  pageTitle: 'text-4xl font-medium mb-3',
  descriptionText: 'text-muted-foreground',
  header: 'bg-card border border-border rounded-3xl p-8 space-y-6',
  labelIcon: 'mb-3 block',
  cardGrid: 'grid grid-cols-2 gap-3',
  stack2: 'space-y-2',
  textareaIcon: 'rounded-xl resize-none',
  descriptionText2: 'text-sm text-muted-foreground',
  footerActions: 'border-t border-border pt-6 space-y-3',
  fullWidthButton: 'w-full rounded-full',
  minuteOptionButton: (selected: boolean) => [
    'rounded-full h-auto py-4',
    selected ? 'border-primary bg-primary/5' : '',
  ].filter(Boolean).join(' '),
} as const;
