export const styles = {
  socialIcon: 'w-5 h-5',
  page: 'min-h-screen flex items-center justify-center px-4 py-12 relative overflow-hidden',
  decorativeShape: 'absolute inset-0 bg-gradient-to-br from-primary/5 via-secondary/20 to-background',
  decorativeShape2: 'absolute top-10 right-10 opacity-10',
  shuttlecockIcon: 'text-primary',
  decorativeShape3: 'absolute bottom-10 left-10 opacity-10',
  decorativeShape4: 'absolute top-1/3 left-20 opacity-5',
  sparklesIcon: 'w-16 h-16 text-primary',
  stack: 'w-full max-w-md space-y-8 relative z-10',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  stack2: 'text-center space-y-6',
  row: 'flex justify-center',
  stack3: 'space-y-2',
  pageTitle: 'text-3xl font-medium',
  descriptionText: 'text-lg text-muted-foreground',
  header: 'bg-card/80 backdrop-blur-sm border-2 border-border rounded-3xl p-10 shadow-2xl shadow-primary/10',
  form: 'space-y-6',
  input: 'rounded-xl h-12',
  cardLink: 'block text-sm text-muted-foreground hover:text-primary transition-colors text-right w-full',
  submitButton: 'w-full rounded-full shadow-lg shadow-primary/20',
  row2: 'flex items-center gap-3 mt-9 mb-6',
  row3: 'h-px bg-border flex-1',
  mutedText: 'text-xs text-muted-foreground',
  stack4: 'space-y-3',
  inlineText: 'w-7 h-7 rounded-full bg-background/90 text-foreground flex items-center justify-center',
  image: 'w-5 h-5 object-contain',
  contentBox: 'mt-5 rounded-xl border border-primary/30 bg-primary/5 p-3 text-center text-sm text-primary',
  centeredBlock: 'text-center',
  mutedText2: 'text-muted-foreground',
  primaryLink: 'text-primary hover:underline font-medium',
  summaryBox: 'bg-secondary/50 rounded-full px-6 py-3 border border-border/50 backdrop-blur-sm',
  row4: 'flex items-center gap-2 text-sm text-muted-foreground',
  socialButton: (tone: string) => [
    'w-full rounded-full h-12 justify-start gap-3 border-2',
    {
      google: 'bg-card border-border text-foreground',
      kakao: 'bg-[#FEE500] border-[#FEE500] text-[#181600]',
      naver: 'bg-[#03C75A] border-[#03C75A] text-white',
      apple: 'bg-foreground border-foreground text-background',
    }[tone],
  ].filter(Boolean).join(' '),
} as const;
