export const styles = {
  socialIcon: 'w-5 h-5',
  appleIcon: 'size-5 translate-y-[-0.5px]',
  page: 'relative flex h-dvh items-center justify-center overflow-hidden bg-background px-4 py-4',
  decorativeShape: 'absolute inset-0 bg-background',
  decorativeShape2: 'absolute top-10 right-10 opacity-10',
  shuttlecockIcon: 'text-primary',
  decorativeShape3: 'absolute bottom-10 left-10 opacity-10',
  decorativeShape4: 'absolute top-1/3 left-20 opacity-5',
  sparklesIcon: 'w-16 h-16 text-primary',
  stack: 'relative z-10 flex max-h-full w-full max-w-md flex-col gap-3 md:gap-4',
  stack2: 'space-y-4 pt-3 text-center',
  row: 'flex justify-center',
  stack3: 'space-y-2',
  pageTitle: 'text-2xl font-medium md:text-3xl',
  descriptionText: 'text-sm text-muted-foreground md:text-base',
  header: 'rounded-3xl border border-border bg-card/90 p-5 shadow-xl shadow-primary/10 backdrop-blur-sm',
  form: 'space-y-3',
  input: 'h-11 rounded-xl bg-input-background [&:not(:placeholder-shown)]:bg-input-background [&:-webkit-autofill]:[-webkit-text-fill-color:var(--foreground)] [&:-webkit-autofill]:[box-shadow:0_0_0_1000px_var(--input-background)_inset] [&:-webkit-autofill:focus]:[box-shadow:0_0_0_1000px_var(--input-background)_inset]',
  cardLink: 'block text-sm text-muted-foreground hover:text-primary transition-colors text-right w-full',
  submitButton: 'w-full cursor-pointer rounded-full shadow-lg shadow-primary/20',
  row2: 'my-3 flex items-center gap-3',
  row3: 'h-px flex-1 bg-border',
  mutedText: 'text-xs text-muted-foreground',
  stack4: 'space-y-2',
  inlineText: 'flex h-5 w-5 shrink-0 items-center justify-center text-foreground',
  image: 'w-5 h-5 object-contain',
  contentBox: 'mt-5 rounded-xl border border-primary/30 bg-primary/5 p-3 text-center text-sm text-primary',
  centeredBlock: 'pb-2 pt-1 text-center',
  mutedText2: 'text-muted-foreground',
  primaryLink: 'text-primary hover:underline font-medium',
  socialButton: (tone: string) => [
    'h-11 w-full cursor-pointer justify-start gap-3 rounded-full border bg-card px-4 text-foreground shadow-sm transition-all hover:-translate-y-0.5 hover:bg-card hover:shadow-md',
    {
      google: 'border-border hover:border-slate-300',
      kakao: 'border-border hover:border-[#FEE500]',
      naver: 'border-border hover:border-[#03C75A]',
      apple: 'border-border hover:border-foreground/40',
    }[tone],
  ].filter(Boolean).join(' '),
} as const;
