export const styles = {
  page: 'min-h-screen bg-background',
  header: 'border-b border-border bg-card',
  headerInner: 'max-w-7xl mx-auto px-6 py-4 flex items-center justify-between',
  row: 'flex items-center gap-6',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  row2: 'flex gap-2',
  roundButton: 'rounded-full gap-2',
  content: 'max-w-7xl mx-auto px-6 py-8',
  sectionHeader: 'mb-8',
  pageTitle: 'text-4xl font-medium mb-2',
  descriptionText: 'text-muted-foreground',
  grid: 'grid lg:grid-cols-[0.9fr_1.1fr] gap-6 mb-8',
  header2: 'bg-card border border-border rounded-3xl p-6 space-y-5',
  row3: 'flex items-center gap-3',
  sparklesIcon: 'w-5 h-5 text-primary',
  sectionTitle: 'text-2xl font-medium',
  cardGrid: 'grid sm:grid-cols-2 gap-4',
  stack: 'space-y-2',
  selectTrigger: 'rounded-xl',
  statsGrid: 'grid sm:grid-cols-3 gap-3',
  wrapRow: 'flex flex-wrap gap-2',
  cardGrid2: 'grid sm:grid-cols-2 gap-3',
  summaryBox: 'rounded-2xl bg-secondary/40 p-4',
  mediaRow: 'flex items-start gap-3',
  shieldAlertIcon: 'w-5 h-5 text-primary mt-0.5',
  summaryText: 'font-medium',
  descriptionText2: 'text-sm text-muted-foreground',
  stack2: 'space-y-4',
  header3: 'bg-card border border-border rounded-2xl p-6',
  betweenRow: 'flex items-start justify-between mb-6',
  row4: 'flex-1',
  row5: 'flex items-center gap-4 mb-4',
  badge: 'bg-primary text-primary-foreground',
  statsGrid2: 'grid grid-cols-3 gap-6 items-center',
  summaryBox2: 'bg-secondary rounded-xl p-4',
  descriptionText3: 'text-xs text-muted-foreground mb-2',
  row6: 'flex items-center gap-2',
  row7: 'w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center',
  labelText: 'text-xs font-medium text-primary',
  centeredBlock: 'text-center',
  mutedText: 'text-2xl font-medium text-muted-foreground',
  summaryBox3: 'mt-4 bg-secondary/50 rounded-xl p-4',
  labelText2: 'font-medium text-foreground',
  wrapRow2: 'flex flex-wrap gap-2 mt-3',
  stack3: 'flex flex-col gap-3 ml-6',
  roundButton2: 'rounded-full whitespace-nowrap',
  summaryBox4: 'bg-secondary rounded-2xl p-12 text-center',
  sparklesIcon2: 'w-16 h-16 text-primary mx-auto mb-4',
  cardTitle: 'font-medium mb-2',
  descriptionText4: 'text-muted-foreground mb-6',
  floatingNotice: 'fixed bottom-6 left-1/2 -translate-x-1/2 bg-card border border-border rounded-full px-5 py-3 shadow-xl text-sm font-medium',
  adjustmentButton: (selected: boolean) => [
    'rounded-xl justify-start gap-2 h-12',
    selected ? 'border-primary bg-primary/5' : '',
  ].filter(Boolean).join(' '),
} as const;
