export const styles = {
  page: 'min-h-screen bg-gradient-to-b from-background to-secondary/20',
  emptyState: 'px-4 py-6',
  logoWrapper: 'justify-center',
  content: 'max-w-2xl mx-auto px-4 pb-12 space-y-8',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  stack: 'text-center space-y-2',
  pageTitle: 'text-4xl font-medium mb-3',
  descriptionText: 'text-muted-foreground',
  header: 'bg-card border border-border rounded-3xl p-8 shadow-sm space-y-8',
  stack2: 'space-y-4',
  row: 'flex items-center gap-3 mb-4',
  badge: 'bg-primary text-primary-foreground',
  mutedText: 'text-sm text-muted-foreground',
  cardGrid: 'grid grid-cols-2 gap-4',
  summaryBox: 'bg-secondary rounded-xl p-4',
  descriptionText2: 'text-xs text-muted-foreground mb-3',
  stack3: 'space-y-2',
  summaryText: 'font-medium',
  footerActions: 'border-t border-border pt-6 space-y-6',
  labelIcon: 'mb-3 block',
  cardGrid2: 'grid grid-cols-2 gap-3',
  stack4: 'bg-secondary/50 rounded-xl p-6 space-y-4',
  mediaRow: 'flex items-start gap-3',
  infoIcon: 'w-5 h-5 text-primary mt-0.5 flex-shrink-0',
  stack5: 'space-y-2 text-sm',
  cardGrid3: 'grid grid-cols-2 gap-4 pt-2',
  input: 'rounded-xl',
  stack6: 'pt-4 space-y-3',
  contentBox: 'rounded-xl border border-primary/30 bg-primary/5 p-3 text-center text-sm text-primary',
  fullWidthButton: 'w-full rounded-full',
  winnerButton: (selected: boolean) => [
    'h-auto py-4 rounded-xl border-2 hover:border-primary hover:bg-primary/5',
    selected ? 'border-primary bg-primary/5' : '',
  ].filter(Boolean).join(' '),
} as const;
