export const styles = {
  page: 'min-h-screen bg-gradient-to-b from-background to-secondary/20',
  emptyState: 'px-4 py-6',
  logoWrapper: 'justify-center',
  content: 'max-w-4xl mx-auto px-4 pb-12 space-y-8',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  stack: 'text-center space-y-4',
  row: 'w-24 h-24 rounded-full bg-primary/20 mx-auto flex items-center justify-center mb-4',
  labelText: 'text-4xl font-medium text-primary',
  pageTitle: 'text-3xl mb-2',
  badge: 'bg-primary text-primary-foreground',
  descriptionText: 'text-sm text-muted-foreground',
  cardGrid: 'grid md:grid-cols-2 gap-4',
  header: 'bg-card border border-border rounded-2xl p-6 text-center',
  row2: 'flex items-center justify-center gap-2 mb-2 text-muted-foreground',
  trophyIcon: 'w-5 h-5',
  inlineText: 'text-sm',
  summaryText: 'text-4xl font-medium text-primary mb-1',
  row3: 'flex items-center justify-center gap-1 text-sm',
  trendingUpIcon: 'w-4 h-4 text-primary',
  inlineText2: 'text-primary',
  mutedText: 'text-muted-foreground',
  header2: 'bg-card border border-border rounded-3xl p-8 space-y-6',
  row4: 'flex items-center gap-3',
  calendarIcon: 'w-5 h-5 text-primary',
  sectionTitle: 'text-2xl font-medium',
  statsGrid: 'grid grid-cols-3 gap-4',
  summaryBox: 'bg-secondary rounded-xl p-4 text-center',
  summaryText2: 'text-3xl font-medium text-primary mb-1',
  descriptionText2: 'text-3xl font-medium text-muted-foreground mb-1',
  mutedText2: 'text-center text-sm text-muted-foreground',
  cardGrid2: 'grid grid-cols-2 md:grid-cols-6 gap-4',
  summaryText3: 'text-2xl font-medium mb-1',
  footerActions: 'pt-6 border-t border-border',
  cardTitle: 'text-lg font-medium mb-4',
  summaryBox2: 'bg-secondary rounded-2xl p-4',
  calendarGrid: 'grid grid-cols-7 gap-2 mb-2',
  mutedText3: 'text-center text-sm font-medium text-muted-foreground',
  stack2: 'space-y-2',
  calendarGrid2: 'grid grid-cols-7 gap-2',
  descriptionText3: 'text-sm text-muted-foreground mt-4 text-center',
  header3: 'bg-card border border-border rounded-3xl p-8 space-y-4',
  summaryBox3: 'rounded-2xl bg-secondary/40 p-5',
  summaryText4: 'font-medium mb-3',
  stack3: 'space-y-2 text-sm',
  stack4: 'space-y-3',
  summaryBox4: 'bg-secondary rounded-xl p-4',
  betweenRow: 'flex items-center justify-between mb-2',
  row5: 'flex items-center gap-2',
  labelText2: 'text-sm font-medium',
  labelText3: 'font-medium',
  fullWidthButton: 'w-full rounded-full',
  calendarDay: (day: number | null, exercised: boolean) => [
    'aspect-square flex items-center justify-center rounded-lg text-sm',
    day === null
      ? ''
      : exercised
      ? 'bg-primary text-primary-foreground font-medium'
      : 'bg-background text-muted-foreground',
  ].filter(Boolean).join(' '),
  resultBadge: (win: boolean) => (win ? 'bg-primary text-primary-foreground' : ''),
} as const;
