export const styles = {
  page: 'min-h-screen bg-gradient-to-b from-accent/20 to-secondary/20',
  emptyState: 'px-4 py-6',
  logoWrapper: 'justify-center',
  content: 'max-w-md mx-auto px-4 pb-12 space-y-6',
  stack: 'text-center space-y-4',
  row: 'w-24 h-24 rounded-full bg-accent mx-auto flex items-center justify-center animate-pulse',
  bellIcon: 'w-12 h-12 text-accent-foreground',
  badge: 'mb-3 bg-accent text-accent-foreground hover:bg-accent',
  pageTitle: 'text-3xl font-medium mb-2',
  descriptionText: 'text-lg text-muted-foreground',
  stack2: 'bg-card border-2 border-accent rounded-3xl p-8 shadow-lg space-y-6',
  centeredBlock: 'text-center pb-4 border-b border-border',
  descriptionText2: 'text-sm text-muted-foreground mb-2',
  summaryText: 'text-5xl font-medium text-primary',
  stack3: 'space-y-4',
  row2: 'flex items-center gap-2 mb-3',
  usersIcon: 'w-5 h-5 text-primary',
  cardTitle: 'font-medium',
  summaryBox: 'bg-secondary rounded-xl p-4',
  descriptionText3: 'text-sm text-muted-foreground',
  usersIcon2: 'w-5 h-5 text-muted-foreground',
  stack4: 'space-y-2',
  footerActions: 'border-t border-border pt-4 space-y-3 text-sm',
  betweenRow: 'flex justify-between',
  mutedText: 'text-muted-foreground',
  fullWidthButton: 'w-full rounded-full',
  contentBox: 'bg-accent/30 rounded-2xl p-6 border border-accent text-center',
  paragraphText: 'text-sm text-accent-foreground',
} as const;
