export const styles = {
  page: 'relative flex min-h-screen min-w-0 items-center bg-background px-8 py-6',
  shell: 'relative z-10 mx-auto flex w-full max-w-[1600px] flex-col justify-center',
  header: 'mb-8 flex items-center justify-between gap-6',
  title: 'text-[40px] font-medium leading-none tracking-tight text-foreground',
  writeButton: 'h-11 rounded-full px-5 shadow-md shadow-primary/15',
  toolbar: 'mb-4 flex items-center justify-between gap-3',
  search: 'relative max-w-md flex-1 [&_svg]:absolute [&_svg]:left-4 [&_svg]:top-1/2 [&_svg]:h-4 [&_svg]:w-4 [&_svg]:-translate-y-1/2 [&_svg]:text-muted-foreground',
  input: 'h-11 rounded-full border-primary/10 bg-card pl-11',
  count: 'text-xs text-muted-foreground',
  board: 'min-h-[560px] overflow-hidden rounded-[28px] border border-primary/15 bg-card/95 shadow-sm shadow-primary/5',
  boardHeader: 'grid grid-cols-[80px_minmax(0,1fr)_120px_120px_90px] items-center gap-3 border-b border-primary/10 bg-primary/[0.035] px-6 py-4 text-center text-xs font-medium text-muted-foreground [&>span:nth-child(2)]:text-left',
  row: 'grid w-full grid-cols-[80px_minmax(0,1fr)_120px_120px_90px] items-center gap-3 border-b border-primary/10 px-6 py-5 text-center text-sm transition-colors last:border-0 hover:bg-primary/[0.025]',
  number: 'text-xs text-muted-foreground',
  rowTitle: 'flex min-w-0 items-center gap-2 text-left font-medium [&_span]:truncate',
  pin: 'flex h-6 shrink-0 items-center gap-1 rounded-full bg-primary/10 px-2 text-[10px] font-semibold text-primary [&_svg]:h-3 [&_svg]:w-3',
  meta: 'text-xs text-muted-foreground',
  empty: 'flex min-h-[500px] flex-col items-center justify-center text-center text-sm text-muted-foreground [&_svg]:mb-4 [&_svg]:h-10 [&_svg]:w-10 [&_svg]:text-primary/40',
  pagination: 'mt-5 flex min-h-10 items-center justify-center gap-1',
  pageButton: (active = false) => `flex h-9 min-w-9 items-center justify-center rounded-full px-3 text-xs font-medium ${active ? 'bg-primary text-primary-foreground shadow-sm' : 'text-muted-foreground hover:bg-primary/10 hover:text-primary'} disabled:pointer-events-none disabled:opacity-30`,
  overlay: 'fixed inset-0 z-50 flex items-center justify-center bg-foreground/20 p-6 backdrop-blur-sm',
  modal: 'flex max-h-[88vh] w-full max-w-[720px] flex-col overflow-hidden rounded-[28px] border border-primary/15 bg-card shadow-2xl shadow-primary/15',
  modalHeader: 'flex items-center justify-between border-b border-primary/10 px-6 py-5 [&_h2]:text-xl [&_h2]:font-medium [&_button]:rounded-full',
  modalBody: 'min-h-0 overflow-y-auto p-6',
  detailMeta: 'mb-5 flex flex-wrap items-center gap-3 text-xs text-muted-foreground',
  detailContent: 'min-h-[240px] whitespace-pre-wrap rounded-2xl bg-secondary/35 p-5 text-sm leading-7',
  form: 'space-y-5 [&_label>span]:mb-2 [&_label>span]:block [&_label>span]:text-sm [&_label>span]:font-medium',
  titleInput: 'h-11 rounded-xl border-primary/10 bg-input-background',
  textarea: 'min-h-[280px] w-full resize-none rounded-2xl border border-primary/15 bg-input-background p-4 text-sm leading-6 outline-none focus:border-primary',
  pinOption: 'flex items-center justify-between rounded-2xl border border-primary/10 p-4 text-sm',
  modalActions: 'mt-5 flex justify-end gap-2 border-t border-primary/10 pt-5 [&_button]:rounded-full',
  cancelButton: 'border-border text-foreground hover:border-border hover:bg-secondary hover:text-foreground',
} as const;
