export const styles = {
  page: 'min-h-screen bg-background',
  header: 'border-b border-border bg-card sticky top-0 z-10 shadow-sm',
  betweenRow: 'px-6 py-4 flex items-center justify-between',
  row: 'flex items-center gap-4',
  verticalDivider: 'h-6 w-px bg-border',
  pageTitle: 'text-lg font-medium',
  descriptionText: 'text-sm text-muted-foreground',
  row2: 'flex items-center gap-2',
  roundButton: 'rounded-full gap-2',
  monitorIcon: 'w-4 h-4',
  roundButton2: 'rounded-full',
  statsGrid: 'grid grid-cols-3 md:grid-cols-6 gap-3 mb-6',
  header2: 'bg-card border border-border rounded-xl p-4',
  descriptionText2: 'text-xs text-muted-foreground',
  summaryText: 'text-xl font-medium mt-1',
  contentBox: 'p-6',
  panel: 'bg-card border-2 border-primary/20 rounded-3xl p-6 mb-6',
  betweenRow2: 'flex items-center justify-between gap-4 mb-5',
  sectionTitle: 'text-2xl font-medium',
  descriptionText3: 'text-muted-foreground',
  badge: 'bg-primary text-primary-foreground',
  statsGrid2: 'grid md:grid-cols-3 gap-4',
  summaryBox: 'h-full rounded-2xl border border-border bg-secondary/30 p-5 hover:border-primary transition-colors',
  row3: 'w-10 h-10 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-medium mb-4',
  cardTitle: 'text-xl font-medium mb-2',
  grid: 'grid grid-cols-5 gap-4 mb-6',
  card: 'bg-card border-2 border-primary/30 rounded-2xl p-5',
  row4: 'flex items-center gap-3 mb-3',
  userCheckIcon: 'w-5 h-5 text-primary',
  summaryText2: 'text-sm font-medium',
  summaryText3: 'text-3xl font-medium',
  descriptionText4: 'text-xs text-muted-foreground mt-1',
  header3: 'bg-card border border-border rounded-2xl p-5',
  clockIcon: 'w-5 h-5 text-muted-foreground',
  userXIcon: 'w-5 h-5 text-accent-foreground',
  row5: 'bg-secondary/30 rounded-2xl p-4 mb-6 flex items-center gap-3',
  summaryText4: 'text-sm font-medium mr-2',
  statsGrid3: 'grid grid-cols-3 gap-6',
  stack: 'col-span-2 space-y-6',
  betweenRow3: 'flex items-center justify-between mb-4',
  sectionTitle2: 'text-xl font-medium',
  actionButton: 'text-primary',
  cardGrid: 'grid grid-cols-2 gap-4',
  badge2: 'text-xs',
  stack2: 'space-y-2 mb-4',
  smallText: 'text-sm',
  summaryText5: 'font-medium',
  descriptionText5: 'text-center text-xs text-muted-foreground',
  cardGrid2: 'grid grid-cols-2 gap-2',
  fullWidthButton: 'w-full rounded-lg',
  row6: 'flex gap-2',
  stack3: 'space-y-3',
  header4: 'bg-card border border-border rounded-2xl p-4',
  betweenRow4: 'flex items-center justify-between',
  row7: 'flex items-center gap-3 flex-1',
  mutedText: 'text-muted-foreground mx-2',
  summaryBox2: 'bg-secondary/20 rounded-2xl p-8 text-center',
  descriptionText6: 'text-muted-foreground mb-3',
  stack4: 'space-y-6',
  contentBox2: 'bg-gradient-to-br from-accent/20 to-accent/10 border-2 border-accent/40 rounded-2xl p-6',
  row8: 'flex items-center gap-3 mb-4',
  alertCircleIcon: 'w-6 h-6 text-accent-foreground',
  cardTitle2: 'font-medium text-accent-foreground',
  paragraphText: 'text-sm text-accent-foreground/80',
  contentBox3: 'text-sm bg-card/50 rounded-lg p-3',
  badge3: 'mb-1',
  fullWidthButton2: 'w-full rounded-full bg-accent text-accent-foreground hover:bg-accent/90',
  actionButton2: 'text-primary -mr-2',
  stack5: 'space-y-2 max-h-[500px] overflow-y-auto',
  betweenRow5: 'flex items-center justify-between py-2',
  row9: 'w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center',
  labelText: 'text-xs font-medium text-primary',
  badge4: 'bg-primary text-primary-foreground text-xs',
  badge5: 'text-xs border-accent',
  cardTitle3: 'font-medium mb-4',
  summaryBox3: 'rounded-xl bg-secondary/40 p-4',
  betweenRow6: 'flex items-center justify-between mb-2',
  descriptionText7: 'text-sm text-muted-foreground mb-3',
  floatingNotice: 'fixed bottom-6 left-1/2 -translate-x-1/2 bg-card border border-border rounded-full px-5 py-3 shadow-xl text-sm font-medium z-50',
} as const;
