export const styles = {
  page: 'min-h-screen bg-gradient-to-b from-background to-secondary/20',
  emptyState: 'px-4 py-6',
  logoWrapper: 'justify-center',
  content: 'max-w-4xl mx-auto px-4 pb-12 space-y-8',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  stack: 'text-center space-y-2',
  pageTitle: 'text-3xl font-medium',
  descriptionText: 'text-muted-foreground',
  cardGrid: 'grid grid-cols-2 md:grid-cols-4 gap-3',
  header: 'bg-card border border-border rounded-2xl p-5 text-center',
  summaryText: 'text-2xl font-medium text-primary',
  descriptionText2: 'text-sm text-muted-foreground mt-1',
  header2: 'bg-card border border-border rounded-3xl p-6 md:p-8 space-y-5',
  row: 'flex items-center gap-3',
  trophyIcon: 'w-5 h-5 text-primary',
  sectionTitle: 'text-2xl font-medium',
  cardGrid2: 'grid md:grid-cols-2 gap-4',
  summaryBox: 'rounded-2xl bg-secondary/40 p-5',
  descriptionText3: 'text-sm text-muted-foreground',
  summaryText2: 'text-3xl font-medium mt-1',
  paragraphText: 'text-primary text-lg',
  statsGrid: 'grid md:grid-cols-3 gap-4',
  contentBox: 'rounded-2xl border border-border p-5',
  descriptionText4: 'text-sm text-muted-foreground mb-2',
  summaryText3: 'font-medium',
  header3: 'bg-card border border-border rounded-3xl p-6 md:p-8 space-y-4',
  stack2: 'space-y-3',
  summaryBox2: 'rounded-2xl bg-secondary/40 p-4',
  betweenRow: 'flex items-center justify-between mb-3',
  row2: 'flex items-center gap-2',
  paragraphText2: 'text-sm',
  header4: 'bg-card border border-border rounded-3xl p-6 md:p-8 flex items-center justify-between gap-4',
  roundButton: 'rounded-full',
  resultBadge: (win: boolean) => (win ? 'bg-primary text-primary-foreground' : ''),
} as const;
