export const styles = {
  page: 'min-h-screen bg-background',
  header: 'border-b border-border bg-card',
  headerInner: 'max-w-7xl mx-auto px-6 py-4 flex items-center justify-between',
  row: 'flex items-center gap-6',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  roundButton: 'rounded-full gap-2',
  content: 'max-w-7xl mx-auto px-6 py-8',
  sectionHeader: 'mb-6',
  pageTitle: 'text-4xl font-medium mb-2',
  descriptionText: 'text-muted-foreground',
  cardGrid: 'grid grid-cols-2 md:grid-cols-6 gap-3 mb-6',
  header2: 'bg-card border border-border rounded-xl p-4 text-center',
  summaryText: 'text-2xl font-medium text-primary',
  descriptionText2: 'text-sm text-muted-foreground',
  header3: 'bg-card border border-border rounded-2xl p-6 mb-6',
  stack: 'flex flex-col md:flex-row gap-4',
  row2: 'flex-1 relative',
  searchIcon: 'absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-muted-foreground',
  input: 'pl-10 rounded-full',
  selectTrigger: 'w-full md:w-48 rounded-full',
  filterIcon: 'w-4 h-4 mr-2',
  header4: 'bg-card border border-border rounded-2xl overflow-hidden mb-6',
  tableScroll: 'overflow-x-auto',
  table: 'w-full',
  tableHead: 'bg-secondary',
  tableHeaderCell: 'text-left px-5 py-4 text-sm font-medium',
  tableBody: 'divide-y divide-border',
  tableRow: 'hover:bg-secondary/50 transition-colors',
  tableCell: 'px-5 py-4',
  row3: 'flex items-center gap-3',
  row4: 'w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center',
  labelText: 'text-sm font-medium text-primary',
  summaryText2: 'font-medium',
  descriptionText3: 'text-xs text-muted-foreground',
  tableCell2: 'px-5 py-4 text-sm',
  descriptionText4: 'text-xs text-muted-foreground mt-2',
  wrapRow: 'flex flex-wrap gap-2',
  selectTrigger2: 'w-36 rounded-full',
  roundButton2: 'rounded-full',
  roundButton3: 'rounded-full gap-1',
  userMinusIcon: 'w-3 h-3',
  actionButton: 'gap-2',
  header5: 'bg-card border border-border rounded-3xl p-6 space-y-4',
  shieldCheckIcon: 'w-5 h-5 text-primary',
  sectionTitle: 'text-2xl font-medium',
  statsGrid: 'grid md:grid-cols-3 gap-4',
  contentBox: 'rounded-2xl border border-border p-5',
  betweenRow: 'flex items-center justify-between mb-3',
  descriptionText5: 'text-sm text-muted-foreground mb-2',
  paragraphText: 'text-sm',
  modalOverlay: 'fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4',
  header6: 'bg-card border border-border rounded-3xl w-full max-w-lg shadow-2xl',
  betweenRow2: 'flex items-center justify-between p-6 border-b border-border',
  descriptionText6: 'text-sm text-muted-foreground mt-1',
  roundButton4: 'rounded-full w-10 h-10 p-0',
  xIcon: 'w-5 h-5',
  stack2: 'p-6 space-y-4',
  stack3: 'space-y-2',
  textareaIcon: 'min-h-32 rounded-xl',
  footerActions: 'p-6 border-t border-border flex gap-3',
  roundButton5: 'flex-1 rounded-full',
  statusBadge: (active: boolean) => (active ? 'bg-primary text-primary-foreground' : ''),
} as const;
