export const styles = {
  page: 'min-h-screen bg-background pb-20',
  header: 'border-b border-border bg-card sticky top-0 z-10',
  emptyState: 'px-4 py-4',
  logoWrapper: 'justify-center',
  stack: 'px-4 py-6 space-y-6',
  panel: 'bg-card border-2 border-primary/30 rounded-3xl p-8 text-center',
  clockIcon: 'w-12 h-12 text-primary mx-auto mb-4',
  summaryText: 'text-2xl font-medium mb-2',
  descriptionText: 'text-muted-foreground',
  contentBox: 'bg-gradient-to-br from-primary/20 to-primary/5 border-2 border-primary rounded-3xl p-8 text-center',
  row: 'w-12 h-12 rounded-full bg-primary mx-auto mb-4 flex items-center justify-center',
  labelText: 'text-white text-lg font-medium',
  header2: 'bg-card border-2 border-border rounded-3xl p-8 text-center',
  coffeeIcon: 'w-12 h-12 text-muted-foreground mx-auto mb-4',
  contentBox2: 'bg-gradient-to-br from-accent/30 to-accent/10 border-2 border-accent/60 rounded-3xl p-6',
  row2: 'flex items-center gap-3 mb-4',
  row3: 'w-10 h-10 rounded-full bg-accent/40 flex items-center justify-center',
  labelText2: 'text-lg font-medium text-accent-foreground',
  paragraphText: 'text-sm text-accent-foreground/80',
  summaryText2: 'font-medium text-accent-foreground',
  stack2: 'space-y-3',
  card: 'bg-card/50 rounded-2xl p-4',
  descriptionText2: 'text-xs text-muted-foreground mb-1',
  summaryText3: 'font-medium',
  descriptionText3: 'text-sm text-muted-foreground mb-3 px-1',
  statsGrid: 'grid grid-cols-3 gap-3',
  header3: 'bg-card border border-border rounded-2xl p-5 text-center',
  summaryText4: 'text-3xl font-medium text-foreground mb-1',
  descriptionText4: 'text-xs text-muted-foreground',
  summaryText5: 'text-3xl font-medium text-primary mb-1',
  descriptionText5: 'text-3xl font-medium text-muted-foreground mb-1',
  floatingNotice: 'fixed bottom-0 left-0 right-0 bg-card border-t border-border px-4 py-4 space-y-3',
  row4: 'flex gap-3',
  link: 'flex-1',
  fullWidthButton: 'w-full rounded-full',
  userCheckIcon: 'w-5 h-5 mr-2',
  restButton: (resting: boolean) => [
    'w-full rounded-full',
    resting ? 'border-primary bg-primary/5 text-primary' : '',
  ].filter(Boolean).join(' '),
} as const;
