export const styles = {
  page: 'relative flex h-dvh items-center justify-center overflow-hidden bg-background px-4 py-4',
  decorativeShape: 'absolute inset-0 bg-background',
  decorativeShape2: 'absolute top-10 right-10 opacity-10',
  shuttlecockIcon: 'text-primary',
  decorativeShape3: 'absolute bottom-10 left-10 opacity-10',
  decorativeShape4: 'absolute top-1/3 left-20 opacity-5',
  sparklesIcon: 'h-16 w-16 text-primary',
  authPanel: 'relative z-10 flex max-h-full w-full max-w-md flex-col gap-3 md:gap-4',
  sectionHeader: 'space-y-4 pt-3 text-center',
  header: 'rounded-3xl border border-border bg-card/90 p-6 shadow-xl shadow-primary/10 backdrop-blur-sm',
  row: 'flex justify-center',
  pageTitle: 'text-2xl font-medium md:text-3xl',
  descriptionText: 'text-sm text-muted-foreground md:text-base',
  form: 'space-y-4',
  stack: 'space-y-2',
  labelRow: 'flex min-h-5 items-center justify-between gap-3',
  fieldMessage: 'min-w-0 text-right text-xs font-medium text-destructive',
  roundedControl: 'h-11 rounded-xl bg-input-background [&:not(:placeholder-shown)]:bg-input-background [&:-webkit-autofill]:[-webkit-text-fill-color:var(--foreground)] [&:-webkit-autofill]:[box-shadow:0_0_0_1000px_var(--input-background)_inset] [&:-webkit-autofill:focus]:[box-shadow:0_0_0_1000px_var(--input-background)_inset]',
  descriptionText2: 'text-sm text-muted-foreground',
  inputGuideText: 'pt-1 text-sm text-muted-foreground',
  ruleList: 'flex flex-wrap gap-1.5',
  ruleDefault: 'rounded-full border border-border bg-muted px-2 py-0.5 text-xs text-muted-foreground',
  ruleValid: 'rounded-full border border-primary/30 bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary',
  submitButton: 'w-full cursor-pointer rounded-full shadow-lg shadow-primary/20',
  secondaryButton: 'w-full cursor-pointer rounded-full shadow-none hover:border-primary/50 hover:bg-primary/10 hover:text-primary',
  completionContent: 'space-y-5 py-2 text-center',
  completionText: 'text-sm leading-6 text-muted-foreground',
  completionButton: 'w-full cursor-pointer rounded-full shadow-lg shadow-primary/20',
  summaryBox: 'rounded-2xl border border-border bg-secondary/40 p-5',
  cardTitle: 'mb-2 font-medium',
  stack2: 'space-y-2 text-sm leading-6 text-muted-foreground',
  stack3: 'mt-5 space-y-4',
  descriptionText3: 'text-sm text-muted-foreground text-center',
  centeredBlock: 'pb-2 pt-1 text-center',
  mutedText: 'text-muted-foreground',
  primaryLink: 'font-medium text-primary hover:underline',
} as const;
