export const styles = {
  page: 'min-h-screen bg-gradient-to-b from-background to-secondary/20 flex items-center justify-center p-4',
  authPanel: 'w-full max-w-md',
  sectionHeader: 'text-center mb-8',
  sectionHeader2: 'justify-center mb-6',
  header: 'bg-card border border-border rounded-3xl p-8 shadow-lg',
  row: 'w-16 h-16 rounded-full bg-primary/20 mx-auto flex items-center justify-center mb-4',
  mailIcon: 'w-8 h-8 text-primary',
  pageTitle: 'text-3xl font-medium mb-2',
  descriptionText: 'text-muted-foreground',
  form: 'space-y-6',
  stack: 'space-y-2',
  roundedControl: 'rounded-xl',
  descriptionText2: 'text-sm text-muted-foreground',
  submitButton: 'w-full rounded-full',
  arrowLeftIcon: 'w-4 h-4 mr-2',
  summaryBox: 'bg-secondary rounded-2xl p-6 mb-6',
  cardTitle: 'font-medium mb-2',
  stack2: 'space-y-2 text-sm text-muted-foreground',
  stack3: 'space-y-3',
  descriptionText3: 'text-sm text-muted-foreground text-center',
  centeredBlock: 'text-center mt-6',
  primaryLink: 'text-primary hover:underline',
} as const;
