const panel = 'min-w-0 overflow-hidden rounded-[26px] border border-primary/15 bg-card/95 shadow-sm shadow-primary/5';
export const styles = {
  page: 'relative flex h-dvh min-w-0 flex-1 overflow-x-hidden overflow-y-auto bg-background px-4 py-8 [scrollbar-gutter:stable] md:px-8',
  pageShell: 'mx-auto my-auto w-full max-w-[1200px] space-y-5',
  pageHeader: 'mb-5 [&_h1]:text-[40px] [&_h1]:font-medium [&_h1]:leading-none [&_p]:mt-3 [&_p]:text-sm [&_p]:text-muted-foreground',
  panel: `${panel} p-6`,
  segmented: 'flex w-fit gap-1 rounded-full bg-secondary/60 p-1',
  segmentButton: (active: boolean) => `h-10 rounded-full px-5 text-sm font-medium transition-all ${active ? 'bg-primary text-primary-foreground shadow-sm shadow-primary/20' : 'text-muted-foreground hover:bg-primary/10 hover:text-primary'}`,
  mmrSummary: 'flex items-center gap-5 [&>span]:flex [&>span]:h-14 [&>span]:w-14 [&>span]:items-center [&>span]:justify-center [&>span]:rounded-2xl [&>span]:bg-primary/10 [&>span]:text-primary [&>span_svg]:h-6 [&>span_svg]:w-6 [&_small]:text-sm [&_small]:text-muted-foreground [&_strong]:mt-1 [&_strong]:block [&_strong]:text-3xl [&_strong]:font-medium [&>p]:ml-auto [&>p]:flex [&>p]:items-center [&>p]:gap-1.5 [&>p]:rounded-full [&>p]:px-4 [&>p]:py-2 [&>p]:text-sm [&>p_svg]:h-4 [&>p_svg]:w-4',
  change: (value: number) => value > 0 ? 'bg-emerald-50 text-emerald-700' : value < 0 ? 'bg-destructive/10 text-destructive' : 'bg-secondary text-muted-foreground',
  chartWrap: 'relative mt-8 rounded-2xl border border-primary/10 bg-primary/[0.02] px-12 pb-5 pt-6',
  chartAxis: 'absolute inset-y-6 left-3 flex flex-col justify-between text-[10px] text-muted-foreground',
  lineChart: 'h-[340px] w-full overflow-visible border-b border-l border-primary/10 [&_polyline]:stroke-primary [&_polyline]:stroke-[2.4] [&_polyline]:drop-shadow-sm',
  chartDates: 'mt-3 flex justify-between text-xs text-muted-foreground',
  panelHeading: 'flex items-center gap-3 border-b border-primary/10 pb-5 [&>svg]:h-5 [&>svg]:w-5 [&>svg]:text-primary [&_h2]:text-lg [&_h2]:font-medium [&_p]:mt-1 [&_p]:text-xs [&_p]:text-muted-foreground',
  historyList: 'divide-y divide-primary/10 [&>div]:grid [&>div]:grid-cols-[160px_minmax(0,1fr)_80px] [&>div]:items-center [&>div]:py-4 [&_time]:text-sm [&_time]:text-muted-foreground [&_span]:text-sm [&_strong]:justify-self-end [&_strong]:rounded-full [&_strong]:px-3 [&_strong]:py-1.5 [&_strong]:text-xs',
  filters: 'mt-5 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5 [&_label>span]:mb-2 [&_label>span]:block [&_label>span]:text-xs [&_label>span]:font-medium [&_input]:h-10 [&_input]:rounded-xl [&_[data-slot=select-trigger]]:h-10 [&_[data-slot=select-trigger]]:w-full [&_[data-slot=select-trigger]]:rounded-xl',
  filterInput: 'border-primary/10 focus-visible:border-primary focus-visible:ring-primary/20 [color-scheme:light]',
  selectTrigger: 'border-primary/10 focus-visible:border-primary focus-visible:ring-primary/20 data-[state=open]:border-primary/30 data-[state=open]:ring-[3px] data-[state=open]:ring-primary/10',
  selectContent: 'border-primary/15',
  selectItem: 'cursor-pointer focus:bg-primary/10 focus:text-primary data-[highlighted]:bg-primary/10 data-[highlighted]:text-primary',
  listHeader: 'flex items-center justify-between border-b border-primary/10 pb-5 [&>div]:flex [&>div]:items-center [&>div]:gap-2 [&>div>svg]:h-5 [&>div>svg]:w-5 [&>div>svg]:text-primary [&>div>strong]:text-lg [&>span]:rounded-full [&>span]:bg-primary/10 [&>span]:px-3 [&>span]:py-1.5 [&>span]:text-xs [&>span]:font-medium [&>span]:text-primary',
  matchList: 'divide-y divide-primary/10',
  matchRow: 'grid min-w-0 grid-cols-[40px_minmax(0,1fr)_90px_20px] items-center gap-4 py-5 transition-colors hover:text-primary [&>div]:min-w-0 [&>div>strong]:block [&>div>strong]:truncate [&>div>strong]:text-sm [&>div>small]:mt-1 [&>div>small]:flex [&>div>small]:items-center [&>div>small]:gap-1 [&>div>small]:text-xs [&>div>small]:text-muted-foreground [&>div>small_svg]:h-3.5 [&>div>small_svg]:w-3.5 [&>div>p]:mt-2 [&>div>p]:truncate [&>div>p]:text-xs [&>div>p]:text-muted-foreground [&>b]:text-center [&>b]:text-lg [&>svg]:h-4 [&>svg]:w-4 [&>svg]:text-muted-foreground',
  result: (win: boolean) => `flex h-10 w-10 items-center justify-center rounded-xl text-xs font-semibold ${win ? 'bg-primary text-primary-foreground' : 'bg-secondary text-muted-foreground'}`,
  pagination: 'flex min-h-9 items-center justify-center gap-1',
  paginationArrow: 'flex h-9 w-9 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-primary/10 hover:text-primary disabled:pointer-events-none disabled:opacity-30 [&_svg]:h-4 [&_svg]:w-4',
  paginationPage: (active: boolean) => `flex h-9 min-w-9 items-center justify-center rounded-full px-3 text-xs font-medium transition-colors ${active ? 'bg-primary text-primary-foreground shadow-sm shadow-primary/20' : 'text-muted-foreground hover:bg-primary/10 hover:text-primary'}`,
  empty: 'mt-5 flex min-h-52 flex-col items-center justify-center rounded-2xl border border-dashed border-primary/15 bg-primary/[0.02] text-center [&_svg]:h-6 [&_svg]:w-6 [&_svg]:text-primary [&_strong]:mt-3 [&_strong]:text-sm [&_strong]:text-muted-foreground',
} as const;
