export const operationStyles = {
  page: 'min-h-screen min-w-[1024px] bg-background text-foreground', header: 'sticky top-0 z-30 border-b border-border bg-card',
  headerInner: 'mx-auto grid h-16 max-w-[1480px] grid-cols-[1fr_auto_1fr] items-center gap-8 px-8', logoSlot: 'justify-self-start', nav: 'flex items-center justify-center gap-1',
  navItem: (active: boolean) => `flex h-11 items-center gap-2 rounded-xl px-4 text-sm font-bold transition-colors ${active ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-secondary hover:text-foreground'}`,
  displayLink: 'flex h-11 items-center gap-2 justify-self-end rounded-xl border border-border px-4 text-sm font-bold hover:border-primary hover:bg-primary/5 hover:text-primary',
  iconSm: 'h-4 w-4', icon: 'h-5 w-5', content: 'mx-auto flex min-h-[calc(100vh-4rem)] w-full max-w-[1480px] flex-col justify-center px-8 py-7', titleRow: 'mb-6 flex items-end justify-between gap-6',
  title: 'text-3xl font-black tracking-tight', description: 'mt-2 text-base text-muted-foreground', actions: 'flex items-center gap-2',
  primaryButton: 'h-12 rounded-xl px-5 text-base font-bold', outlineButton: 'h-12 rounded-xl border-border px-5 text-base font-bold hover:border-primary hover:bg-primary/5 hover:text-primary',
  card: 'rounded-2xl border border-border bg-card p-5 shadow-sm', sectionTitle: 'text-lg font-black', sectionDescription: 'mt-1 text-sm text-muted-foreground',
  stats: 'grid grid-cols-6 gap-3', stat: 'rounded-2xl border border-border bg-card p-4', statLabel: 'text-sm font-bold text-muted-foreground', statValue: 'mt-2 text-3xl font-black',
  grid2: 'grid grid-cols-2 gap-5', grid3: 'grid grid-cols-3 gap-4', stack: 'space-y-4', row: 'flex items-center gap-3', between: 'flex items-center justify-between gap-4',
  alert: 'flex items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 font-bold text-amber-800',
  empty: 'rounded-2xl border border-dashed border-border bg-card px-6 py-12 text-center text-muted-foreground',
  badge: 'rounded-full px-3 py-1 text-sm font-bold', teamBox: 'rounded-xl bg-secondary/60 p-4', teamTitle: 'mb-2 text-sm font-black text-primary', player: 'flex items-center justify-between py-1.5 text-base font-bold',
  tableWrap: 'overflow-hidden rounded-2xl border border-border bg-card', table: 'w-full border-collapse text-left', th: 'bg-secondary/70 px-4 py-3 text-sm font-black text-muted-foreground', td: 'border-t border-border px-4 py-3 text-sm',
  select: 'h-12 rounded-xl border-border bg-background px-3 text-base font-bold', input: 'h-12 rounded-xl border-border text-base', label: 'mb-2 block text-sm font-black',
  modalBackdrop: 'fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-6', modal: 'w-full max-w-2xl rounded-3xl border border-border bg-card p-6 shadow-2xl',
  modalTitle: 'text-2xl font-black', divider: 'my-5 border-t border-border', notice: 'fixed bottom-6 right-6 z-50 rounded-2xl bg-foreground px-5 py-4 font-bold text-background shadow-xl',
  dangerButton: 'h-11 rounded-xl border border-red-200 bg-white px-4 font-bold text-red-600 hover:bg-red-50 hover:text-red-700',
};
