export const styles = {
  page: 'min-h-screen bg-background',
  header: 'border-b border-border bg-card',
  headerInner: 'max-w-7xl mx-auto px-6 py-4 flex items-center justify-between',
  row: 'flex items-center gap-6',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  roundButton: 'rounded-full gap-2',
  header2: 'fixed top-20 left-1/2 -translate-x-1/2 bg-card border border-border rounded-full px-5 py-3 shadow-xl text-sm font-medium z-50',
  content: 'max-w-7xl mx-auto px-6 py-8',
  sectionHeader: 'mb-8 text-center',
  pageTitle: 'text-4xl font-medium mb-2',
  descriptionText: 'text-muted-foreground',
  grid: 'grid md:grid-cols-5 gap-4 mb-8',
  header3: 'bg-card border border-border rounded-2xl p-6 text-center',
  row2: 'w-12 h-12 rounded-full bg-primary/10 mx-auto flex items-center justify-center mb-3',
  usersIcon: 'w-6 h-6 text-primary',
  summaryText: 'text-3xl font-medium text-primary mb-1',
  descriptionText2: 'text-sm text-muted-foreground',
  header4: 'bg-card border border-border rounded-3xl p-8 mb-8',
  sectionTitle: 'text-2xl font-medium mb-6',
  tableScroll: 'overflow-x-auto',
  table: 'w-full',
  tableHead: 'bg-secondary',
  tableHeaderCell: 'text-left px-6 py-4 text-sm font-medium rounded-tl-xl',
  tableHeaderCell2: 'text-center px-6 py-4 text-sm font-medium',
  tableHeaderCell3: 'text-center px-6 py-4 text-sm font-medium rounded-tr-xl',
  tableBody: 'divide-y divide-border',
  tableRow: 'hover:bg-secondary/50 transition-colors',
  tableCell: 'px-6 py-4',
  row3: 'flex items-center gap-3',
  row4: 'w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center',
  labelText: 'text-sm font-medium text-primary',
  labelText2: 'font-medium',
  tableCell2: 'px-6 py-4 text-center font-medium',
  tableCell3: 'px-6 py-4 text-center',
  cardGrid: 'grid md:grid-cols-2 gap-6',
  header5: 'bg-card border border-border rounded-2xl p-6',
  cardTitle: 'font-medium mb-4',
  stack: 'space-y-3',
  betweenRow: 'flex items-center justify-between',
  inlineText: 'text-sm',
  tablePanel: 'w-32 h-2 bg-secondary rounded-full overflow-hidden',
  progressFill: 'h-full bg-primary',
  labelText3: 'text-sm font-medium',
  stack2: 'space-y-3 text-sm',
  betweenRow2: 'flex justify-between',
  contentBox: 'mt-6 bg-accent/20 rounded-2xl p-6 border border-accent',
  cardTitle2: 'font-medium mb-3 text-accent-foreground',
  paragraphText: 'text-sm text-accent-foreground/80 mb-4',
  badge: 'border-accent text-accent-foreground',
  matchTypeBar: (width: string) => ({ width }),
} as const;
