export const styles = {
  page: 'min-h-screen bg-gradient-to-b from-background to-secondary/20',
  emptyState: 'px-4 py-6',
  logoWrapper: 'justify-center',
  content: 'max-w-3xl mx-auto px-4 pb-12 space-y-8',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  stack: 'text-center space-y-2',
  pageTitle: 'text-4xl font-medium mb-3',
  descriptionText: 'text-muted-foreground',
  header: 'bg-card border border-border rounded-3xl p-8 space-y-8',
  stack2: 'space-y-6',
  row: 'flex items-center gap-3 pb-4 border-b border-border',
  userIcon: 'w-5 h-5 text-primary',
  sectionTitle: 'text-2xl font-medium',
  stack3: 'space-y-4',
  row2: 'flex items-center justify-center mb-6',
  row3: 'w-24 h-24 rounded-full bg-primary/20 flex items-center justify-center',
  labelText: 'text-4xl font-medium text-primary',
  stack4: 'space-y-2',
  input: 'rounded-xl',
  descriptionText2: 'text-sm text-muted-foreground',
  cardGrid: 'grid grid-cols-2 gap-4',
  footerActions: 'space-y-6 pt-8 border-t border-border',
  betweenRow: 'flex items-center justify-between',
  summaryText: 'font-medium',
  cardGrid2: 'grid sm:grid-cols-2 gap-3 pt-2',
  betweenRow2: 'flex items-center justify-between rounded-xl border border-border p-3',
  inlineText: 'text-sm',
  cardGrid3: 'grid sm:grid-cols-2 gap-4',
  summaryBox: 'rounded-2xl bg-secondary/40 p-5',
  summaryText2: 'font-medium mb-1',
  descriptionText3: 'text-sm text-muted-foreground mb-4',
  roundButton: 'rounded-full',
  descriptionText4: 'text-sm text-muted-foreground mt-3',
  stack5: 'space-y-3',
  betweenRow3: 'flex items-center justify-between rounded-xl border border-border p-4',
  labelText2: 'text-sm font-medium text-primary',
  footerActions2: 'pt-8 border-t border-border space-y-4',
  contentBox: 'rounded-xl border border-primary/30 bg-primary/5 p-3 text-center text-sm text-primary',
  fullWidthButton: 'w-full rounded-full',
  fullWidthButton2: 'w-full rounded-full gap-2 text-destructive hover:text-destructive',
  logOutIcon: 'w-5 h-5',
} as const;
