const basePanel = 'rounded-[26px] border border-primary/15 bg-card/95 shadow-sm shadow-primary/5';

export const styles = {
  page: 'relative h-dvh min-w-0 flex-1 overflow-x-hidden overflow-y-auto bg-background px-8 pb-6 pt-2 [scrollbar-gutter:stable]',
  backgroundGlowTop: 'pointer-events-none fixed right-12 top-16 h-72 w-72 rounded-full bg-primary/5 blur-3xl',
  backgroundGlowBottom: 'pointer-events-none fixed bottom-10 left-72 h-64 w-64 rounded-full bg-primary/5 blur-3xl',
  pageShell: 'relative z-10 mx-auto w-full max-w-[1600px] space-y-5 pt-5',
  pageHeader: 'mb-4 flex items-end justify-between [&_h1]:text-[40px] [&_h1]:font-medium [&_h1]:leading-none [&_h1]:tracking-tight',
  feedback: (tone: 'success' | 'error') => [
    'rounded-2xl border px-5 py-4 text-sm font-medium shadow-sm',
    tone === 'success'
      ? 'border-primary/20 bg-primary/[0.04] text-primary'
      : 'border-destructive/25 bg-destructive/[0.06] text-destructive',
  ].join(' '),
  panel: `${basePanel} min-w-0 overflow-hidden`,
  dangerSection: `${basePanel} min-w-0 overflow-hidden`,
  panelHeader: 'flex min-h-[82px] items-center justify-between gap-5 border-b border-primary/10 bg-gradient-to-r from-primary/[0.035] via-card to-card px-6 py-4',
  panelTitleBox: 'flex min-w-0 items-center gap-3 [&_h2]:text-xl [&_h2]:font-medium [&_p]:mt-1 [&_p]:text-sm [&_p]:text-muted-foreground',
  panelIconBox: 'flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-primary/[0.07] text-primary [&_svg]:h-5 [&_svg]:w-5',
  panelBody: 'min-w-0 p-6',
  settingsGrid: 'grid grid-cols-1 items-start gap-5',
  settingsForm: 'space-y-4 [&_label]:block [&_label>span]:mb-2 [&_label>span]:block [&_label>span]:text-sm [&_label>span]:font-medium [&_label>small]:mt-2 [&_label>small]:block [&_label>small]:text-xs [&_label>small]:text-muted-foreground',
  hiddenInput: 'hidden',
  imageSetting: (active: boolean) => [
    'flex min-h-[190px] flex-col items-center justify-center text-center transition-colors',
    active ? 'rounded-2xl bg-primary/[0.04]' : '',
    '[&_img]:h-32 [&_img]:w-32 [&_img]:shrink-0 [&_img]:rounded-[28px] [&_img]:object-cover [&_img]:shadow-md [&>div]:mt-5 [&>div]:flex [&>div]:gap-2',
  ].join(' '),
  profileFallback: 'flex h-32 w-32 items-center justify-center rounded-[28px] bg-primary/10 text-4xl font-medium text-primary shadow-md shadow-primary/10',
  roundButton: 'h-10 rounded-full border-primary/15 px-4 hover:border-primary/30 hover:bg-primary/10 hover:text-primary',
  destructiveButton: 'hover:border-destructive/40 hover:bg-destructive/90 hover:text-white',
  smallRoundButton: 'h-9 rounded-full border-primary/15 px-4 hover:border-primary/30 hover:bg-primary/10 hover:text-primary',
  textButton: 'rounded-full text-primary hover:bg-primary/10 hover:text-primary',
  dangerTextButton: 'rounded-full text-destructive hover:bg-destructive/5 hover:text-destructive',
  iconButton: 'rounded-full hover:bg-primary/10 hover:text-primary [&_svg]:h-4 [&_svg]:w-4',
  input: 'h-11 rounded-xl border-primary/10 bg-input-background focus-visible:border-primary focus-visible:ring-primary/20',
  selectTriggerWide: 'h-11 rounded-xl border-primary/10 bg-input-background focus-visible:border-primary focus-visible:ring-primary/20 data-[state=open]:border-primary/30 data-[state=open]:ring-[3px] data-[state=open]:ring-primary/10',
  selectItem: 'cursor-pointer focus:bg-primary/10 focus:text-primary data-[highlighted]:bg-primary/10 data-[highlighted]:text-primary',
  saveButton: 'ml-auto flex h-10 rounded-full px-5 shadow-md shadow-primary/15 hover:bg-primary/90 hover:text-primary-foreground',
  noticeBox: 'rounded-2xl border border-primary/10 bg-primary/[0.035] p-5 text-sm [&>strong]:block [&>span]:mt-2 [&>span]:block [&>span]:text-muted-foreground',
  permissionOptionList: 'space-y-2',
  permissionOption: (active: boolean) => `flex w-full cursor-pointer items-center justify-between rounded-xl border px-4 py-3 text-left transition-colors disabled:cursor-not-allowed disabled:opacity-50 ${active ? 'border-primary/25 bg-primary/[0.07]' : 'border-primary/10 bg-card hover:border-primary/20 hover:bg-primary/[0.035]'} [&>span:first-child>strong]:block [&>span:first-child>strong]:text-sm [&>span:first-child>small]:mt-1 [&>span:first-child>small]:block [&>span:first-child>small]:text-xs [&>span:first-child>small]:text-muted-foreground [&>span:last-child]:flex [&>span:last-child]:shrink-0 [&>span:last-child]:items-center [&>span:last-child]:gap-1.5 [&>span:last-child]:rounded-full [&>span:last-child]:px-3 [&>span:last-child]:py-1.5 [&>span:last-child]:text-xs [&>span:last-child]:font-medium ${active ? '[&>span:last-child]:bg-primary [&>span:last-child]:text-primary-foreground' : '[&>span:last-child]:bg-secondary [&>span:last-child]:text-muted-foreground'} [&>span:last-child>svg]:h-3.5 [&>span:last-child>svg]:w-3.5`,
  appInstallBox: 'flex items-center justify-between gap-4 rounded-2xl border border-primary/10 p-4 [&_strong]:block [&_strong]:text-sm [&_span]:mt-1 [&_span]:block [&_span]:text-xs [&_span]:text-muted-foreground',
  appInstallButton: 'h-10 shrink-0 rounded-full border-primary/15 hover:border-primary/15 hover:bg-card hover:text-foreground',
  dangerZone: 'flex min-h-[130px] items-center gap-6 rounded-2xl border border-destructive/15 bg-destructive/[0.025] p-6 [&_strong]:shrink-0 [&_strong]:text-sm [&_p]:min-w-0 [&_p]:flex-1 [&_p]:text-xs [&_p]:leading-5 [&_p]:text-muted-foreground [&_button]:shrink-0',
  modalOverlay: 'fixed inset-0 z-50 flex items-center justify-center bg-foreground/20 p-6 backdrop-blur-sm',
  modal: 'max-h-[92vh] w-full max-w-[520px] rounded-[28px] border border-primary/15 bg-card shadow-2xl shadow-primary/15',
  modalHeader: 'flex items-center justify-between border-b border-primary/10 px-6 py-5 [&_h2]:text-xl [&_h2]:font-medium',
  modalBody: 'max-h-[calc(88vh-74px)] overflow-y-auto p-6',
  confirmContent: 'flex flex-col items-center text-center [&>p]:mt-4 [&>p]:max-w-md [&>p]:text-sm [&>p]:leading-6 [&>p]:text-muted-foreground [&_.modal-actions]:mt-5 [&_.modal-actions]:flex [&_.modal-actions]:justify-center [&_.modal-actions]:gap-2 [&_.modal-actions_button]:rounded-full',
  warningIconBox: 'flex h-14 w-14 items-center justify-center rounded-2xl bg-destructive/10 text-destructive [&_svg]:h-6 [&_svg]:w-6',
  mutedText: 'p-6 text-sm text-muted-foreground',
  toast: 'fixed left-1/2 bottom-6 z-50 w-max max-w-[calc(100vw-2rem)] -translate-x-1/2 rounded-2xl bg-foreground px-5 py-3 text-center text-sm font-medium text-background shadow-lg',
} as const;
