export const styles = {
  page: 'min-h-screen flex items-center justify-center px-4 py-12 relative overflow-hidden',
  decorativeShape: 'absolute inset-0 bg-gradient-to-br from-primary/5 via-secondary/20 to-background',
  decorativeShape2: 'absolute top-20 right-20 opacity-10',
  awardIcon: 'w-24 h-24 text-primary',
  decorativeShape3: 'absolute bottom-20 left-20 opacity-10',
  heartIcon: 'w-16 h-16 text-primary',
  decorativeShape4: 'absolute top-1/2 right-10 opacity-5',
  shuttlecockIcon: 'text-primary',
  stack: 'w-full max-w-md space-y-8 relative z-10',
  backLink: 'inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors',
  arrowLeftIcon: 'w-4 h-4',
  stack2: 'text-center space-y-6',
  row: 'flex justify-center',
  stack3: 'space-y-2',
  pageTitle: 'text-3xl font-medium',
  descriptionText: 'text-lg text-muted-foreground',
  header: 'bg-card/80 backdrop-blur-sm border-2 border-border rounded-3xl p-10 shadow-2xl shadow-primary/10',
  form: 'space-y-5',
  input: 'rounded-xl h-11',
  cardGrid: 'grid grid-cols-2 gap-4',
  contentBox: 'rounded-xl border border-primary/30 bg-primary/5 p-3 text-center text-sm text-primary',
  submitButton: 'w-full rounded-full shadow-lg shadow-primary/20',
  centeredBlock: 'text-center',
  mutedText: 'text-muted-foreground',
  primaryLink: 'text-primary hover:underline font-medium',
  pill: 'bg-gradient-to-r from-secondary/50 to-primary/10 rounded-full px-6 py-3 border border-border/50 backdrop-blur-sm',
  row2: 'flex items-center gap-2 text-sm',
} as const;
