export const styles = {
  page: 'relative flex h-dvh items-center justify-center overflow-hidden bg-background px-4 py-4',
  decorativeShape: 'absolute inset-0 bg-background',
  decorativeShape2: 'absolute top-10 right-10 opacity-10',
  decorativeShape3: 'absolute bottom-10 left-10 opacity-10',
  decorativeShape4: 'absolute top-1/3 left-20 opacity-5',
  shuttlecockIcon: 'text-primary',
  sparklesIcon: 'h-16 w-16 text-primary',
  stack: 'relative z-10 flex max-h-full w-full max-w-md flex-col gap-3 md:gap-4',
  stack2: 'space-y-4 pt-3 text-center',
  row: 'flex justify-center',
  stack3: 'space-y-2',
  pageTitle: 'text-2xl font-medium md:text-3xl',
  descriptionText: 'text-sm text-muted-foreground md:text-base',
  header: 'rounded-3xl border border-border bg-card/90 p-5 shadow-xl shadow-primary/10 backdrop-blur-sm',
  form: 'space-y-3',
  input: 'h-11 rounded-xl bg-input-background [&:not(:placeholder-shown)]:bg-input-background [&:-webkit-autofill]:[-webkit-text-fill-color:var(--foreground)] [&:-webkit-autofill]:[box-shadow:0_0_0_1000px_var(--input-background)_inset] [&:-webkit-autofill:focus]:[box-shadow:0_0_0_1000px_var(--input-background)_inset]',
  cardGrid: 'grid grid-cols-2 gap-3',
  contentBox: 'rounded-xl border border-primary/30 bg-primary/5 p-3 text-center text-sm text-primary',
  submitButton: 'w-full cursor-pointer rounded-full shadow-lg shadow-primary/20',
  centeredBlock: 'pb-2 pt-1 text-center',
  mutedText: 'text-muted-foreground',
  primaryLink: 'text-primary hover:underline font-medium',
} as const;
