import { apiClient } from './apiClient';

export type OperationSession = { sessionId: number; groupId: number; groupName: string; title: string; startsAt: string; endsAt: string | null; place: string; sessionType?: string; courtCount: number; disabledCourtNumbers: number[]; status: string; entryCode?: string | null; matchAssignmentStarted?: boolean };
export type OperationPlayer = { attendanceId: number; name: string; grade: string };
export type OperationTeam = { teamNumber: number; players: OperationPlayer[] };
export type OperationQueue = { queueId: number; queueOrder: number; status: string; courtNumber: number | null; matchType: string; playStyle?: string; calledAt: string | null; score?: number; explanations?: string[]; teams: OperationTeam[] };
export type OperationMatch = { matchId: number; courtNumber: number; matchType: string; playStyle?: string; status: string; calledAt: string; startedAt: string; endedAt: string | null; teamAScore: number; teamBScore: number; scoreEntered?: boolean; resultUpdated?: boolean; resultUpdateReason?: string | null; teams: OperationTeam[]; mmrResults?: { name: string; before: number; after: number; delta: number }[]; resultHistory?: { previousScore: string; newScore: string; reason: string; modifiedBy: string; modifiedAt: string }[] };
export type OperationParticipant = { attendanceId: number; name: string; participantType: string; gender: string; ageGroup: string; grade: string; affiliation?: string | null; doublesMmr: number; mixedMmr: number; attendanceStatus: string; playStatus: string; games: number; consecutivePlayCount: number; consecutiveRestCount: number; arrivedAt?: string | null; lateExpectedAt: string | null; lateReason?: string | null; memo: string | null; wins?: number; losses?: number; winRate?: number; pointsFor?: number; pointsAgainst?: number; mmrDelta?: number };
export type MatchPlanResult = { generatedCount: number; queues: OperationQueue[]; targetGamesPerParticipant: number; participantPlans: { attendanceId: number; name: string; projectedGames: number; addedGames: number; targetReached: boolean }[]; message: string };
export type ParticipantRelation = { relationId: number; firstAttendanceId: number; firstName: string; secondAttendanceId: number; secondName: string; relationType: string };
export type DashboardResponse = OperationSession & { summary: Record<string, number>; currentMatches: OperationMatch[]; queues: OperationQueue[]; pendingResults: OperationMatch[]; participants: OperationParticipant[]; alerts: string[]; lastUpdatedAt: string };
export type ParticipantResponse = OperationSession & { participants: OperationParticipant[]; relations: ParticipantRelation[] };
export type QueueResponse = OperationSession & { queues: OperationQueue[]; relations: ParticipantRelation[]; participants: OperationParticipant[]; hasMatchHistory: boolean };
export type MatchResponse = OperationSession & { matches: OperationMatch[]; queues: OperationQueue[]; participants: OperationParticipant[] };
export type ReportResponse = OperationSession & { summary: { participantCount: number; totalMatchCount: number; averageMatchCount: number; pendingResultCount: number }; participantRecords: OperationParticipant[]; matches: OperationMatch[]; analysis: { matchTypes: Record<string, number>; courtMatches: Record<string, number>; partnerDuplicatePairs: number; opponentDuplicatePairs: number; totalPlayMinutes: number } };

const now = new Date();
const iso = (minuteOffset = 0) => new Date(now.getTime() + minuteOffset * 60_000).toISOString();
const team = (teamNumber: number, players: [number, string, string][]): OperationTeam => ({ teamNumber, players: players.map(([attendanceId, name, grade]) => ({ attendanceId, name, grade })) });
const demoSession: OperationSession = { sessionId: 1, groupId: 1, groupName: '강남 배드민턴 클럽', title: '6월 정기 운동', startsAt: iso(-80), endsAt: iso(100), place: '강남구민회관', courtCount: 3, disabledCourtNumbers: [], status: 'IN_PROGRESS', entryCode: 'SP260619', matchAssignmentStarted: false };
const demoParticipants: OperationParticipant[] = [
  [1, '홍길동', 'MEMBER', 'MALE', 'THIRTIES', 'B', 1280, 'PLAYING', 3, 1, 0], [2, '김민수', 'MEMBER', 'MALE', 'FORTIES', 'B', 1255, 'PLAYING', 3, 1, 0],
  [3, '박서연', 'MEMBER', 'FEMALE', 'THIRTIES', 'B', 1268, 'PLAYING', 2, 1, 0], [4, '이유진', 'GUEST', 'FEMALE', 'FORTIES', 'C', 1100, 'PLAYING', 2, 1, 0],
  [5, '최정우', 'MEMBER', 'MALE', 'FIFTIES', 'C', 1130, 'NEXT_UP', 1, 0, 2], [6, '정하늘', 'MEMBER', 'FEMALE', 'FORTIES', 'C', 1115, 'NEXT_UP', 1, 0, 2],
  [7, '강수진', 'MEMBER', 'FEMALE', 'FIFTIES', 'D', 970, 'NEXT_UP', 2, 0, 1], [8, '윤태호', 'GUEST', 'MALE', 'FIFTIES', 'D', 950, 'NEXT_UP', 2, 0, 1],
  [9, '임지훈', 'MEMBER', 'MALE', 'SIXTIES', 'C', 1095, 'AVAILABLE', 2, 0, 1], [10, '한미영', 'MEMBER', 'FEMALE', 'FIFTIES', 'D', 980, 'RESTING', 3, 1, 0],
].map(([attendanceId, name, participantType, gender, ageGroup, grade, mmr, playStatus, games, consecutivePlayCount, consecutiveRestCount]) => ({ attendanceId: Number(attendanceId), name: String(name), participantType: String(participantType), gender: String(gender), ageGroup: String(ageGroup), grade: String(grade), doublesMmr: Number(mmr), mixedMmr: Number(mmr), attendanceStatus: 'ARRIVED', playStatus: String(playStatus), games: Number(games), consecutivePlayCount: Number(consecutivePlayCount), consecutiveRestCount: Number(consecutiveRestCount), lateExpectedAt: null, memo: null }));
const demoQueues: OperationQueue[] = [{ queueId: 21, queueOrder: 1, status: 'WAITING', courtNumber: null, matchType: 'ANY', playStyle: 'FUN', calledAt: null, score: 92.4, explanations: ['2회 연속 휴식 참가자를 우선 배정했어요.', '파트너 중복이 없는 조합이에요.', '고정·회피 조합 설정을 반영했어요.'], teams: [team(1, [[5, '최정우', 'C'], [6, '정하늘', 'C']]), team(2, [[7, '강수진', 'D'], [8, '윤태호', 'D']])] }];
const demoMatches: OperationMatch[] = [{ matchId: 31, courtNumber: 1, matchType: 'MIXED_DOUBLES', playStyle: 'FUN', status: 'PLAYING', calledAt: iso(-20), startedAt: iso(-18), endedAt: null, teamAScore: 0, teamBScore: 0, teams: [team(1, [[1, '홍길동', 'B'], [3, '박서연', 'B']]), team(2, [[2, '김민수', 'B'], [4, '이유진', 'C']])] }];
const demoRelations: ParticipantRelation[] = [{ relationId: 1, firstAttendanceId: 5, firstName: '최정우', secondAttendanceId: 6, secondName: '정하늘', relationType: 'FIXED_PARTNER' }];
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
export const isDemoSession = (sessionId?: string) => sessionId === 'demo';

const demoDashboard = (): DashboardResponse => ({ ...clone(demoSession), summary: { attendanceCount: 10, availableCount: 1, waitingCount: 0, nextUpCount: 4, callingCount: 0, playingCount: 4, restingCount: 1, leftCount: 0, absentCount: 0, currentMatchCount: 1, queueCount: 1, pendingResultCount: 1 }, currentMatches: clone(demoMatches), queues: clone(demoQueues), pendingResults: clone(demoMatches), participants: clone(demoParticipants), alerts: ['경기 후보 큐가 부족해요.'], lastUpdatedAt: iso() });
const demoReport = (): ReportResponse => ({ ...clone(demoSession), summary: { participantCount: 10, totalMatchCount: 7, averageMatchCount: 2.4, pendingResultCount: 1 }, participantRecords: demoParticipants.map((item, index) => ({ ...item, wins: Math.max(0, item.games - 1), losses: item.games ? 1 : 0, winRate: item.games ? Math.round((item.games - 1) * 1000 / item.games) / 10 : 0, pointsFor: item.games * 21, pointsAgainst: item.games * 17, mmrDelta: index % 2 ? -4 : 6 })), matches: clone(demoMatches), analysis: { matchTypes: { ANY: 2, MENS_DOUBLES: 2, WOMENS_DOUBLES: 1, MIXED_DOUBLES: 2 }, courtMatches: { 1: 3, 2: 2, 3: 2 }, partnerDuplicatePairs: 1, opponentDuplicatePairs: 2, totalPlayMinutes: 126 } });

const auth = { auth: true } as const;
export const sessionOperationApi = {
  dashboard: (id: string) => isDemoSession(id) ? Promise.resolve(demoDashboard()) : apiClient.get<DashboardResponse>(`/session-operations/sessions/${id}/dashboard`, auth),
  participants: (id: string) => isDemoSession(id) ? Promise.resolve({ ...clone(demoSession), participants: clone(demoParticipants), relations: clone(demoRelations) }) : apiClient.get<ParticipantResponse>(`/session-operations/sessions/${id}/participants`, auth),
  changeParticipantStatus: (id: string, attendanceId: number, playStatus: string) => isDemoSession(id) ? Promise.resolve({ ...clone(demoParticipants.find(item => item.attendanceId === attendanceId)!), playStatus }) : apiClient.patch<OperationParticipant>(`/session-operations/sessions/${id}/participants/${attendanceId}/status`, { playStatus }, auth),
  changeParticipantAttendance: (id: string, attendanceId: number, body: { attendanceStatus: string; expectedArrivalAt?: string; lateReason?: string }) => isDemoSession(id) ? Promise.resolve({ ...clone(demoParticipants.find(item => item.attendanceId === attendanceId)!), attendanceStatus: body.attendanceStatus, lateExpectedAt: body.expectedArrivalAt ?? null, lateReason: body.lateReason ?? null }) : apiClient.patch<OperationParticipant>(`/session-operations/sessions/${id}/participants/${attendanceId}/attendance`, body, auth),
  updateParticipantMemo: (id: string, attendanceId: number, memo: string) => isDemoSession(id) ? Promise.resolve({ ...clone(demoParticipants.find(item => item.attendanceId === attendanceId)!), memo }) : apiClient.patch<OperationParticipant>(`/session-operations/sessions/${id}/participants/${attendanceId}/memo`, { memo }, auth),
  updateCourts: (id: string, disabledCourtNumbers: number[]) => isDemoSession(id) ? Promise.resolve({ ...clone(demoSession), disabledCourtNumbers }) : apiClient.patch<OperationSession>(`/session-operations/sessions/${id}/courts`, { disabledCourtNumbers }, auth),
  saveRelation: (id: string, body: { firstAttendanceId: number; secondAttendanceId: number; relationType: string }) => isDemoSession(id) ? Promise.resolve({ relationId: Date.now(), firstAttendanceId: body.firstAttendanceId, firstName: demoParticipants.find(item => item.attendanceId === body.firstAttendanceId)?.name ?? '', secondAttendanceId: body.secondAttendanceId, secondName: demoParticipants.find(item => item.attendanceId === body.secondAttendanceId)?.name ?? '', relationType: body.relationType }) : apiClient.post<ParticipantRelation>(`/session-operations/sessions/${id}/relations`, body, auth),
  deleteRelation: (id: string, relationId: number) => isDemoSession(id) ? Promise.resolve() : apiClient.delete<void>(`/session-operations/sessions/${id}/relations/${relationId}`, auth),
  queues: (id: string) => isDemoSession(id) ? Promise.resolve({ ...clone(demoSession), queues: clone(demoQueues), relations: clone(demoRelations), participants: clone(demoParticipants), hasMatchHistory: false }) : apiClient.get<QueueResponse>(`/session-operations/sessions/${id}/queues`, auth),
  generate: (id: string, body: unknown) => isDemoSession(id) ? Promise.resolve({ generatedCount: demoQueues.length, queues: clone(demoQueues), lowQuality: false, message: '경기 후보를 만들었어요.' }) : apiClient.post<{ generatedCount: number; queues: OperationQueue[]; lowQuality: boolean; message: string }>(`/session-operations/sessions/${id}/matching/generate`, body, auth),
  generatePlan: (id: string, body: unknown) => isDemoSession(id) ? Promise.resolve<MatchPlanResult>({ generatedCount: 3, queues: clone(demoQueues), targetGamesPerParticipant: 1, participantPlans: demoParticipants.map(item => ({ attendanceId: item.attendanceId, name: item.name, projectedGames: item.games + 1, addedGames: 1, targetReached: true })), message: '경기 가능한 참가자 모두에게 1경기 이상을 추가한 전체 대진표를 만들었어요.' }) : apiClient.post<MatchPlanResult>(`/session-operations/sessions/${id}/matching/generate-plan`, body, auth),
  assignEmptyCourts: (id: string) => isDemoSession(id) ? Promise.resolve({ assignedCount: 1, matches: clone(demoMatches), message: '1개 경기를 빈 코트에 배정했어요.' }) : apiClient.post<{ assignedCount: number; matches: OperationMatch[]; message: string }>(`/session-operations/sessions/${id}/queues/assign-empty-courts`, {}, auth),
  callQueue: (id: string, queueId: number, courtNumber?: number) => isDemoSession(id) ? Promise.resolve({ ...clone(demoMatches[0]), matchId: queueId, courtNumber: courtNumber ?? 1, status: 'CALLING' }) : apiClient.post<OperationMatch>(`/session-operations/sessions/${id}/queues/${queueId}/call`, courtNumber ? { courtNumber } : {}, auth),
  createManualQueue: (id: string, body: { teamAIds: number[]; teamBIds: number[]; matchType: string; playStyle: string }) => isDemoSession(id) ? Promise.resolve({ ...clone(demoQueues[0]), queueId: Date.now(), queueOrder: demoQueues.length + 1, matchType: body.matchType, playStyle: body.playStyle }) : apiClient.post<OperationQueue>(`/session-operations/sessions/${id}/queues/manual`, body, auth),
  updateQueue: (id: string, queueId: number, body: { teamAIds: number[]; teamBIds: number[] }) => isDemoSession(id) ? Promise.resolve(clone(demoQueues[0])) : apiClient.patch<OperationQueue>(`/session-operations/sessions/${id}/queues/${queueId}`, body, auth),
  cancelQueue: (id: string, queueId: number) => isDemoSession(id) ? Promise.resolve() : apiClient.post<void>(`/session-operations/sessions/${id}/queues/${queueId}/cancel`, {}, auth),
  reorderQueue: (id: string, queueId: number, queueOrder: number) => isDemoSession(id) ? Promise.resolve({ ...clone(demoQueues[0]), queueId, queueOrder }) : apiClient.patch<OperationQueue>(`/session-operations/sessions/${id}/queues/${queueId}/order`, { queueOrder }, auth),
  matches: (id: string) => isDemoSession(id) ? Promise.resolve({ ...clone(demoSession), matches: clone(demoMatches), queues: clone(demoQueues), participants: clone(demoParticipants.filter(item => !['PLAYING', 'CALLING', 'LEFT', 'ABSENT'].includes(item.playStatus))) }) : apiClient.get<MatchResponse>(`/session-operations/sessions/${id}/matches`, auth),
  cancelMatch: (id: string, matchId: number, reason: string) => isDemoSession(id) ? Promise.resolve({ ...clone(demoMatches[0]), matchId, status: 'CANCELED' }) : apiClient.post<OperationMatch>(`/session-operations/sessions/${id}/matches/${matchId}/cancel`, { reason }, auth),
  startMatch: (id: string, matchId: number) => isDemoSession(id) ? Promise.resolve({ ...clone(demoMatches[0]), matchId, status: 'PLAYING' }) : apiClient.post<OperationMatch>(`/session-operations/sessions/${id}/matches/${matchId}/start`, {}, auth),
  submitResult: (id: string, matchId: number, body: { teamAScore: number; teamBScore: number; scoreEntered: boolean }) => isDemoSession(id) ? Promise.resolve({ ...clone(demoMatches[0]), matchId, ...body, status: 'RESULT_ENTERED', endedAt: iso() }) : apiClient.post<OperationMatch>(`/session-operations/sessions/${id}/matches/${matchId}/result`, body, auth),
  updateResult: (id: string, matchId: number, body: { teamAScore: number; teamBScore: number; scoreEntered?: boolean; reason: string }) => isDemoSession(id) ? Promise.resolve({ ...clone(demoMatches[0]), matchId, ...body, status: 'RESULT_ENTERED', resultUpdated: true }) : apiClient.patch<OperationMatch>(`/session-operations/sessions/${id}/matches/${matchId}/result`, body, auth),
  report: (id: string) => isDemoSession(id) ? Promise.resolve(demoReport()) : apiClient.get<ReportResponse>(`/session-operations/sessions/${id}/report`, auth),
  resetMatches: (id: string) => isDemoSession(id) ? Promise.resolve({ ...demoReport(), summary: { participantCount: demoParticipants.length, totalMatchCount: 0, averageMatchCount: 0, pendingResultCount: 0 }, matches: [] }) : apiClient.delete<ReportResponse>(`/session-operations/sessions/${id}/matches`, auth),
  close: (id: string) => isDemoSession(id) ? Promise.resolve(demoReport()) : apiClient.post<ReportResponse>(`/session-operations/sessions/${id}/close`, {}, auth),
  display: (id: string) => isDemoSession(id) ? Promise.resolve({ ...clone(demoSession), currentMatches: clone(demoMatches), nextMatches: clone(demoQueues), lastUpdatedAt: iso() }) : apiClient.get<OperationSession & { currentMatches: OperationMatch[]; nextMatches: OperationQueue[]; lastUpdatedAt: string }>(`/session-operations/sessions/${id}/display`, auth),
};
